### ISSUE TITLE
Deathadder Elite not recognized on Arch

### ISSUE THREAD

**Issue by bootzin** [polychromatic/polychromatic#140]
I've just recently acquired a razer DeathAdder Elite, and I've been trying to configure its LEDS, but I haven't had any luck so far as I'm constantly getting "Device Not Recognized" error, and I'm kinda lost regarding what to do
I'm running Arch linux with openrazer drivers

This is the openrazer log: https://ptpb.pw/2Z-G

This is the output of `ls -lah /sys/bus/hid/drivers/hid-generic*/`, which is pretty similar to the output of `ls -lah /sys/bus/hid/devices/`: https://ptpb.pw/S0oy (Which leads me to the conclusion that the drivers were successfully bound). Rebooting didn't help either

Any suggestions as to how to progress? The mouse works just fine, I just can't get into configuring its LEDs, or making polychromatic recognize it

**Comment by lah7** [comment]
It's a problem with the daemon. Even by looking at your log, the device itself hasn't been registered by the daemon which is why Polychromatic reports "not recognised" since this app detects a Razer device plugged into the system.

I would have suggested [raising an issue on OpenRazer's repository](https://github.com/openrazer/openrazer/issues), as one of those guys use Arch and will know what to do, but this looks similar to https://github.com/openrazer/openrazer/issues/331. Have you tried installing the kernel headers and then re-installed OpenRazer and Polychromatic?

**Comment by bootzin** [comment]
Well, that actually has solved the issue. It was a matter of updating the system after installing the headers
Thanks for the help
