### ISSUE TITLE
Macro Keys Support for DeathAdder Chroma 

### ISSUE THREAD

**Issue by mritunjaymusale** [polychromatic/polychromatic#142]
I have DA-Chroma and could you guys setup an UI for managing the macro keys,in it's current state  the macro keys are fully functional with the existing driver just can't configure them.
Another request:
How to do I setup  a custom profile,because when the polychromatic service starts it sets my dpi to 1800 rather than 1000

OS:
Ubuntu 17.10

**Comment by lah7** [comment]
> setup an UI for managing the macro keys,in it's current state the macro keys are fully functional with the existing driver just can't configure them.

Polychromatic depends on the daemon exposing functions to control functionality/lighting, but neither the daemon/python library supports keybindings right now -- but there may be _external_ solutions which I haven't looked into yet. :thinking: 

> How to do I setup a custom profile

The current version can only set up custom static lighting for keyboards, but in the next major version, there will be much better "profile" support, but without key mapping at this stage (keypads face the same issue)

> because when the polychromatic service starts it sets my dpi to 1800 rather than 1000

Could it be possible `openrazer-daemon` or the hardware causes this? The latest stable version of Polychromatic does not set the DPI when the tray applet starts. Hardware-wise, 1800 is the second preset, so it's possible unless software instructs it otherwise, it might be resetting each time.

In future, there will be a background Polychromatic service that can optionally enforce settings on login, which would likely address this issue. In the meantime, you can write a custom script and run that at login:

```
#!/usr/bin/env python3
import openrazer.client
mouse = openrazer.client.DeviceManager().devices[0]  # Assuming only device connected
mouse.dpi = (1000,1000)
```
