### ISSUE TITLE
It never saves settings of my Mamba mouse

### ISSUE THREAD

**Issue by shadowc** [polychromatic/polychromatic#148]
Every time I turn on the PC, I have to enter the app and set the settings for me:

Breath - 2 colors (green, purple). Some times even the colors aren't set when I choose the "breath" effect. 

It would be awesome if the app worked!

**Comment by lah7** [comment]
What is the model of your Mamba?

If it's the wireless model -- try seeing if starting the computer with the mouse purely wireless and again purely wired makes any difference to the effect. Apparently this mouse is seen as two, which may contribute to the problem of "not retaining the previous effect" across reboots.

As Polychromatic is just a front-end for the OpenRazer daemon, it uses hardware effects to control the device. For many devices, hardware effects are "remembered" in the firmware across reboots but some Razer devices always start with a default effect until the computer has booted. In that case, the hardware expects the software (Synapse in case of Windows) to tell it what to do.

Polychromatic does "track" the previously selected effect, but has no idea what the device is actually using (the daemon does not support this). This app is undergoing some major changes that will provide "start-up options" which will make managing this easier in future.

There is a workaround in the meantime, add this command to your start-up applications:

```
python3 -c "import openrazer.client; a = openrazer.client.DeviceManager(); a.devices[0].fx.breath_dual(0, 255, 0, 130, 0, 255)"
```

:point_up: This will set a dual breath between green (`0,255,0`) and purple (`130,0,255`) for the first device the daemon sees (assuming it's the only Razer device you have)

-----
The second issue of not being set when clicked could be either a Controller bug or daemon bug (where it doesn't speak to the hardware first time). I'm not sure why this happens. :thinking:

**Comment by lah7** [comment]
That's my mouse too -- I can confirm that it does remember its last effect across power cycles. Now you mention Windows dual boot, it's **highly likely** due to Synapse controlling lighting using "software effects", even though the hardware could do it by itself. So, when the computer powers on, it's going to resort back to a "hardware" effect if a "software" (custom) effect was previously used.

One possible culprit could be firmware version -- mine's `v1.2` (can be seen in Polychromatic's Overview screen)

The second case of "not applying settings" is something I've witnessed before (very, very rarely) with my BlackWidow Chroma keyboard. I was switching between software effects (ripple is the OpenRazer daemon's) and hardware effects, but it's wasn't consistent. Even so, I think this would be [an issue raised on OpenRazer](https://github.com/openrazer/openrazer/issues) if this can be reliably replicated.

I'll leave the issue open until Polychromatic is capable of setting an effect at login. :+1:

**Comment by lah7** [comment]
6 years is a long time. OpenRazer has had a persistence feature for years which helps devices that need help restoring their settings after a power cycle (at login). Polychromatic has also been able to restore a custom effect if it was playing previously (at login too).
