### ISSUE TITLE
cant start polychromatic in opensuse tumbleweed KDE

### ISSUE THREAD

**Issue by cocotugo** [polychromatic/polychromatic#149]
hi, I get segmentation fault when trying to run polychromatic.
i installed all the required libraries listed in the readme.

when i run polychromatic using sudo i get:
Cannot open display "default display"
Segmentation fault

I have openrazer daemon (ver2.3.0) running fine.

**Comment by lah7** [comment]
The application (also the OpenRazer daemon) **should not** be run as root (`sudo`). What happens when you run both of them without `sudo`? Is this happening for the controller, the tray applet or both?

Otherwise, it's likely a problem with your installation -- did you install the [packages from here](https://software.opensuse.org/download.html?project=hardware%3Arazer&package=polychromatic)?

**Comment by cocotugo** [comment]
thanks for your response.
the daemon is running fine (is not run as sudo). (was able to change color with other app)
I did install those packages.
without sudo both polychromatic apps throw 
`Segmentation fault (core dumped)`

**Comment by z3ntu** [comment]
Filed a bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1090405

**Comment by cocotugo** [comment]
thank you.
wonder whats happening under the hood. :/

**Comment by lah7** [comment]
openSUSE is working again! :tada: Turns out segfaults were caused by a missing `python3-gobject-gdk` package, due to the way openSUSE packages this [differently to other distros](https://bugzilla.opensuse.org/show_bug.cgi?id=1090405#c9). It's been added as a dependency, so it will work again on the next system update.
