### ISSUE TITLE
Support for chroma-enabled games ?

### ISSUE THREAD

**Issue by Qik000** [polychromatic/polychromatic#166]
Are there any plans for making the polychromatic cooperate with games that utilize chroma ?

**Comment by lah7** [comment]
Unfortunately not. It's extremely unlikely to be possible since the Linux versions of Chroma-enabled games use Razer's SDK, which is for Windows only.

Even so, [OpenRazer](https://github.com/openrazer/openrazer) would be a better place for such integration, but I don't think it will be possible unless Razer brings their SDK to Linux. Sorry about that :slightly_frowning_face:
