### ISSUE TITLE
Razer BlackWidow Chroma V2 "Device Not Recognised"

### ISSUE THREAD

**Issue by kierun** [polychromatic/polychromatic#177]
I have a Razer BlackWidow Chroma V2 running on Cent OS 7. When I start `polychromatic-controller`, I get a "Device Not Recognised". However, the keyboard works fine.

_What am I doing wrong?_

Some debugging:
```
; lsusb
[…]
Bus 003 Device 002: ID 1532:0221 Razer USA, Ltd 
; uname -a
Linux serval.XXX 4.17.11-1.el7.elrepo.x86_64 #1 SMP Sat Jul 28 09:33:09 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
; dkms status -m openrazer-driver -v 2.3.1                                      
openrazer-driver, 2.3.1, 3.10.0-862.9.1.el7.x86_64, x86_64: installed     
; rpm -qa | ag -i razer
razer-daemon-2.3.1-1.el7.noarch                                                 
python3-razer-2.3.1-1.el7.noarch                                                
razer-kernel-modules-dkms-2.3.1-1.el7.noarch                                    
openrazer-meta-2.3.1-1.el7.noarch
```

**Comment by lah7** [comment]
I'm not familiar with CentOS, but the issue is that the OpenRazer driver isn't installed properly, and so the OpenRazer daemon doesn't find any devices for Polychromatic to use.

**Some suggestions:**

* Is your user in the `plugdev` group?
* Is secure boot enabled? (UEFI systems only) Try turning it off and reinstalling the OpenRazer DKMS package.
* Output of `dkms status openrazer-driver`?
  * Have they been built for the same version of your kernel? (`uname -r`)
* Double check the right Linux kernel headers are installed.
  * The DKMS modules won't build without them and the driver won't work as a result.
  * Are they building for the right version of the kernel?
* Output of `sudo modprobe razerkbd`?

**Comment by kierun** [comment]
> Is your user in the plugdev group?

Yes, it is.

> Is secure boot enabled? (UEFI systems only)

No, legacy mode only. This is an old machine.

>  Output of dkms status openrazer-driver?

```
Error! Could not locate dkms.conf file.                                         
File: /var/lib/dkms/openrazer-driver/1.0.0/source/dkms.conf does not exist.  
```

> Are they building for the right version of the kernel?

I think that's the problem… To get the keyboard to be recognised as a keyboard (and not a mouse!), I need the 4.X kernel which is not normally available in CentOS. The kernel-ml does not have headers.

> Output of sudo modprobe razerkbd?

```modprobe: FATAL: Module razerkbd not found.```

**Comment by kierun** [comment]
Removed the kernel-ml, (back to the `hid-recorder` hack to get keyboard working), removed all traces of the driver, and re-installed the driver. Polychomatic now works.

Urgh.

```
; dkms status openrazer-driver                                                  
openrazer-driver, 2.3.1, 3.10.0-862.9.1.el7.x86_64, x86_64: installed           
; sudo modprobe razerkbd
; echo $?
0
```

**Comment by kierun** [comment]
Oh, forgot to say *many thanks indeed for taking the time to help.*
