### ISSUE TITLE
[Feature Request] Brightness level

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [polychromatic/polychromatic#190]
![brightness](https://user-images.githubusercontent.com/3637857/50375834-00434800-0615-11e9-848c-6f5688f3689b.png)

It's seems that right now it's impossible to set brightness level, only off/on modes are available.

**Comment by lah7** [comment]
It's due to the OpenRazer daemon stating it has the `active` capability, which is specified by devices that can only toggle their "brightness" on/off.

A minor tweak is needed for your https://github.com/openrazer/openrazer/pull/743 pull request - please remove:

`'set_logo_active', 'get_logo_active'` and `'set_scroll_active', 'get_scroll_active'`

**Comment by GrigoriyMikhalkin** [comment]
@GrigoriyMikhalkin Thanks! That solved problem.
