### ISSUE TITLE
Polychromatic applet unresponsive - How do I disable it

### ISSUE THREAD

**Issue by statsandthings** [polychromatic/polychromatic#191]
I'm using Polychromatic version `0.3.12-stable` on Ubuntu 18.04 and it works fine. The applet, however, is unresponsive and doesn't respond to any input or mouse clicks. It works intermittently directly after a reboot, but I don't like intermittent. How do I disable the applet? It doesn't appear I can do so through the settings. I'm fine opening the full polychromatic to change settings as needed.

**Comment by lah7** [comment]
For quite some time, the latest codebase has an option to toggle the tray applet from the Controller's preferences **(Option 1)**

![Screenshot_20210614_210311](https://user-images.githubusercontent.com/13032135/121952283-f0270200-cd53-11eb-9220-690b0605837e.png)

a21f25f5a382ca435b23c4070bbffa0c3fabe6be took this a step further and will show an option **(Option 2)** if the tray applet is the only component installed. The Ubuntu/Debian packaging supports this, so since the Controller doesn't have to be installed, there will still be a way to disable auto starting if the user prefers to start manually.

![image](https://user-images.githubusercontent.com/13032135/121952775-98d56180-cd54-11eb-8073-fea203a07882.png)
