### ISSUE TITLE
[Proposal] Key mapping integration in Controller GUI using Pystromo as backend

### ISSUE THREAD

**Issue by lah7** [polychromatic/polychromatic#193]
As mentioned in https://github.com/openrazer/openrazer/issues/167#issuecomment-452164735 (and again in https://github.com/openrazer/openrazer/issues/769#issuecomment-462003193) by @TherinS, there's a configurable tool known as [Pystromo](https://github.com/byrongibson/Pystromo) that would serve our desires to have configurable key remapping functionality for Razer devices.

I'd be interested to add a GUI within Polychromatic Controller that can create config files for use with this tool, in the _**distant future**_ ([after v1.1.0](https://polychromatic.app/docs/roadmap/)). **However:**

* Pystromo needs porting to Python 3.
  * [A fork started a port, but it doesn't seem to work](https://github.com/booms8/Pystromo), it seems.
* There's no evidence of it working yet.
* The [original author hasn't updated it in 7 years](https://github.com/byrongibson/Pystromo).

#### What needs to be decided:

* **How _integrated_?**
  * **OpenRazer would be desirable location instead** for the backend, since everyone can utilse the highly requested functionality, and Polychromatic can stick with its strength as _the frontend_.
  * Pystromo should be packaged as a separate, optional feature.
* **How to handle superuser privileges?**
  * Either the application runs as root (tricky as it's inconvenient) or configure some rules files so any user can read input using `uinput` -- :warning:  This would introduce **security concerns** as any application could theoretically read raw input of the device!
* **How well does this work alongside the OpenRazer daemon?**
* **How do we find out the key input values for mapping a Razer keypad?**

#### There is also the work of [razer_test](https://github.com/z3ntu/razer_test), which will eventually be the userspace successor to OpenRazer's codebase.
  * In theory, this is an easier project to implement key remapping functionality then bolting onto the existing daemon, as it's all in userspace. It would be wise for interested contributors to focus efforts on that project instead.
  * <strike>`razer_test` hasn't implemented the OpenRazer Python library yet, so it will be **incompatible** with Polychromatic at the moment.</strike>
    * **Update:** [A shim is available.](https://github.com/z3ntu/openrazer-shim)

------
:bulb:  This issue is just a proposed idea. Feedback welcome.

----

* I tried Pystromo 6.0.0 (python2) and got it to somewhat work, but if I remember correctly, it mapped the keyboard and not just a specific key on the keypad. :-1: 
  * This will be because of how the OpenRazer driver handles the device... or it's in a "no driver" mode.
* I attempted a quick, dirty port to `python3` using `2to3`, but some refactoring would be needed.

**Comment by TherinS** [comment]
Thank you for CCing me in this email.  I would like to be included in further communication, should you see fit.

The only point I would like to correct is the comment of Pystromo having "no evidence of it working yet".  Pystromo works great in Ubuntu 16.04 and the couple flavors I have tried
it on.  My issue with the program is that while it seems to be running in Ubuntu 18.04, it does not remap the keys correctly on my n52 or Tartarus.  It just needs someone who knows troubleshooting Python scripts/programs to find out why it stopped working in 18.04 and make adjustments/patch/fork as needed.  If that could be resolved then
I would use it again instead of KeyboardingMaster.

I have also been able to remap a Madcats game controller and my Razer mouse, but the mouse LED did not pass-through; it treated the directions of the mouse movement as keyboard presses.  This is because Pystromo rebinds USB input devices' as keyboard presses.  I could make the buttons on the mouse act as any keyboard key (or make macro keypresses), but that was also the limitation of the mouse LED.

Pystromo could be expanded to rebind USB keypads, old controllers, etc, as long as the kernel recognized the device as an input device and had a driver to interact with.  Pystromo does NOT provide driver support for devices like the Logitech G13 gameboard; by default the kernel does not have a driver to interact with it.

I am going to try out a live USB of PCLinuxOS - MATE x64 to see if Pystromo runs out of the box on it, and that will be another distro it works on if things go well.


On Sun, Feb 10, 2019 at 5:16 PM, Luke Horwell <notifications@github.com> wrote:

As mentioned in openrazer/openrazer#167 (comment)<https://github.com/openrazer/openrazer/issues/167#issuecomment-452164735> (and again in openrazer/openrazer#769 (comment)<https://github.com/openrazer/openrazer/issues/769#issuecomment-462003193>) by @TherinS<https://github.com/TherinS>, there's a configurable tool known as Pystromo<https://github.com/byrongibson/Pystromo> that would serve our desires to have configurable key remapping functionality for Razer devices.

I'd be interested to add a GUI within Polychromatic Controller that can create config files for use with this tool, in the distant future (after v1.1.0<https://polychromatic.app/docs/roadmap/>). However:

  *   Pystromo needs porting to Python 3.
     *   A fork started a port, but it doesn't seem to work<https://github.com/booms8/Pystromo>, it seems.
  *   There's no evidence of it working yet.
  *   The original author hasn't updated it in 7 years<https://github.com/byrongibson/Pystromo>.

What needs to be decided:

  *   How integrated?
     *   OpenRazer would be desirable location instead for the backend, since everyone can utilse the highly requested functionality, and Polychromatic can stick with its strength as the frontend.
     *   Pystromo should be packaged as a separate, optional feature.
  *   How to handle superuser privileges?
     *   Either the application runs as root (tricky as it's inconvenient) or configure some rules files so any user can read input using uinput -- ⚠️ This would introduce security concerns as any application could theoretically read raw input of the device!
  *   How well does this work alongside with the OpenRazer daemon?
  *   How do we find out the key input values for mapping a Razer keypad?

There is also the work of razer_test<https://github.com/z3ntu/razer_test>, which will eventually be the userspace successor to OpenRazer's codebase.

  *   In theory, this is an easier project to implement key remapping functionality then bolting onto the existing daemon, as it's all in userspace. It would be wise for interested contributors to focus efforts on that project instead.
  *   razer_test hasn't implemented the OpenRazer Python library yet, so it will be incompatible with Polychromatic at the moment.

________________________________

💡 This issue is just a proposed idea. Feedback welcome.

________________________________

  *   I tried Pystromo 6.0.0 (python2) and got it to somewhat work, but if I remember correctly, it mapped the keyboard and not just a specific key on the keypad. 👎
  *   I attempted a dirty port to python3 using 2to3, but some refactoring would be needed.

**Comment by lah7** [comment]
A year later, I'm considering https://github.com/boppreh/keyboard instead as it's a working Python 3 high level API that would be better suited for this project.

Key mapping integration isn't a top priority, so it will still be a while before any key mapping functionality is integrated.

See also: #223
