### ISSUE TITLE
Add Support for Razer Blade Advanced (2019)

### ISSUE THREAD

**Issue by rsimmonsjr** [polychromatic/polychromatic#194]
Currently the system doesn't see the Blade Advanced that just came out. Also would be great to have support for gaming vs non-gaming mode.

**Comment by lah7** [comment]
I see you've opened https://github.com/openrazer/openrazer/issues/775. When this is implemented, the device will automagically appear in Polychromatic. :+1:

Regarding gaming vs non-gaming mode... is this the usual game mode (disable ALT+F4 & Windows keys) or does this hardware have other features?

**Comment by rsimmonsjr** [comment]
In the Razer advanced they have a new feature for game mode. That is what I
am talking about. Non game mode makes the system not run so hot.



*Robert E Simmons Jr. MSc.
<https://www.linkedin.com/in/robert-simmons-a3985240/>*Chief Technology
Officer

New York, NY, USA
+1 (512) 906-9814

**Comment by lah7** [comment]
I see. :thinking: Since it's power management, this is a back-end feature request, _possibly_ one for OpenRazer to consider. My guess is that Synapse on Windows will tweak Windows' settings to scale down CPU frequency and favour energy saving options over performance. I imagine an equivalent integration will be needed for Linux. For now, there are already [dedicated tools to tweak power management](https://wiki.archlinux.org/index.php/laptop#Power_management) (as documented on Arch).

Since Polychromatic is primarily a frontend for OpenRazer's capabilities, we can re-open this issue and add a toggle if the power management feature is implemented. :+1:

**Comment by rsimmonsjr** [comment]
Uhh why did this get closed. Still need polychromatic support on the Blade Advanced 2019. That you dont do gaming mode is fine but still the driver should work .

**Comment by lah7** [comment]
Device support is tracked on OpenRazer's repository: https://github.com/openrazer/openrazer/issues/775

I closed here as there's nothing on this end this frontend project can do. Once OpenRazer adds driver support and releases a new version, the device will appear in Polychromatic.
