### ISSUE TITLE
No Spectrum Effect on Ornata

### ISSUE THREAD

**Issue by eduardosousaufjf** [polychromatic/polychromatic#195]
I have a Razer Ornata (green only) and there is no way to set it to the Spectrum effect on Linux, it is not even listed. I am using Ubuntu 18 btw, but already tested on Ubuntu 16 and had the same problem.

**Comment by lah7** [comment]
Polychromatic (frontend) gets its data from OpenRazer (backend), but according to Razer's marketing page, the **Razer Ornata** doesn't support Spectrum, which is the RGB colour changing cycle.

* https://www.razer.com/gb-en/gaming-keyboards-keypads/razer-ornata

This is the [Orana commit in OpenRazer](https://github.com/openrazer/openrazer/commit/0655860905e67ee2338ea5cf0211ed4cbefb2406#diff-043eec42d6c1a4943b21bd8e44bc8c2cR575) which doesn't support spectrum, but the [Ornata Chroma](https://github.com/openrazer/openrazer/commit/ebb56d5e2f90fda079fb09b3d9ed3786027924da#diff-043eec42d6c1a4943b21bd8e44bc8c2cR319) does.

**Comment by eduardosousaufjf** [comment]
I use Spectrum in Windows, so it actually works.

**Comment by lah7** [comment]
You can try [raising an issue on OpenRazer's repository](https://github.com/openrazer/openrazer/issues) in case the hardware does support spectrum, but it is possible that it's a "software effect" that Synapse is producing. Polychromatic is building a feature to create/play animated effects, since OpenRazer's effects (except ripple) at the moment are all dependant on the hardware.
