### ISSUE TITLE
Unable to load daemon in Arch for Deathadder Elite

### ISSUE THREAD

**Issue by dj25380** [polychromatic/polychromatic#201]
I'm new to Arch is there something im missing?

Terminal output:

Verbose enabled
/usr/bin/polychromatic-controller:290: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass("polychromatic-controller", "polychromatic-controller")
/usr/bin/polychromatic-controller:292: DeprecationWarning: Gtk.Widget.modify_bg is deprecated
  self.window.modify_bg(Gtk.StateType(0), Gdk.Color(0, 0, 0))
Set scale to: 1.0
Initialised Window.
Version 0.3.12-stable
Loading daemon...
ERROR: Daemon Not Found.
ERROR: Could not connect to the Daemon Device Manager!

**Comment by lah7** [comment]
The OpenRazer daemon likely isn't running or couldn't start because of an error. Check the output of:

    openrazer-daemon -Fv

(`-v` verbose, `-F` foreground)

If it's not starting because of `plugdev`, please run this and reboot:

    sudo gpasswd -a <USERNAME> plugdev

There's more on [OpenRazer's troubleshooting page](https://github.com/openrazer/openrazer/wiki/Troubleshooting).

**Comment by lah7** [comment]
The OpenRazer daemon likely isn't running or couldn't start because of an error. Check the output of:

    openrazer-daemon -Fv

(`-v` verbose, `-F` foreground)

If it's not starting because of `plugdev`, please run this and reboot:

    sudo gpasswd -a <USERNAME> plugdev

There's more on [OpenRazer's troubleshooting page](https://github.com/openrazer/openrazer/wiki/Troubleshooting).

**Comment by dj25380** [comment]
That gave me a bit of progress, I tried find how to fix this next issue and its really confusing, I don't have secure boot and for the life of me I don't understand what modprobe is.

Terminal output:

Verbose enabled
/usr/bin/polychromatic-controller:290: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass("polychromatic-controller", "polychromatic-controller")
/usr/bin/polychromatic-controller:292: DeprecationWarning: Gtk.Widget.modify_bg is deprecated
  self.window.modify_bg(Gtk.StateType(0), Gdk.Color(0, 0, 0))
Set scale to: 1.0
Initialised Window.
Version 0.3.12-stable
Loading daemon...
Gathering devices...
WARN: Daemon did not return any devices.
