### ISSUE TITLE
How to change default DPI values in applet

### ISSUE THREAD

**Issue by mayd-in** [polychromatic/polychromatic#202]
There are 6 different DPI values in applet (ie. 200, 800, 1800). I would like to change these but I know software does not allow this for now.

Is there any configuration file to make modifications to these values?

**Comment by lah7** [comment]
The applet pre-determines values based on the maximum DPI for a device. Since there isn't a configuration file yet, you can modify `/usr/bin/polychromatic-tray-applet` at these lines:

https://github.com/polychromatic/polychromatic/blob/730bdb19fdae3d0e3c6b8d179de9d702362e19d0/polychromatic-tray-applet#L772-L778

:point_up: Bear in mind any changes would be overwritten on the next release (which is quite a while yet). :bulb: But a way to edit these values is a good idea, I'll add that to my list, thanks!

**Comment by kevchu3** [comment]
+1 on this

I've customized the stages of my mouse's DPI based on @lah7's comment above, and thus in the Polychromatic UI, I have a dropdown with these custom values.  However, there are two physical buttons on my Naga Chroma mouse (as many others) corresponding to DPI stage up and down.  There is an open issue (https://github.com/polychromatic/polychromatic/issues/163) to customize the DPI stages, and I just wanted to add some feedback that configuring these DPI values here only affects the UI, and doesn't actually customize those DPI stages (which appear to be more difficult based on https://github.com/polychromatic/polychromatic/issues/163#issuecomment-392244841)

Would customizing those DPI stages be more of an issue to be worked on with https://github.com/openrazer/openrazer or Polychromatic?

**Comment by lah7** [comment]
Setting DPI stages using the hardware buttons would be for OpenRazer to implement.

https://github.com/openrazer/openrazer/pull/1138 looks like a good step in that direction since it would allow us to sync software and hardware DPI intervals.
