### ISSUE TITLE
Gaming Mode for Keyboards Disables Alt-Tab

### ISSUE THREAD

**Issue by bauer41s4** [polychromatic/polychromatic#206]
I'm running into an issue on my razer keyboard where I active gaming mode (prevents alt-f4 and the super key) that also seems to prevent any alt tabbing with the left-alt key. I can still alt tab with right-alt though.

**Comment by lah7** [comment]
Polychromatic isn't responsible for the gaming mode behaviour. Rather, it's the OpenRazer driver/daemon. Please raise the issue on their repository:

https://github.com/openrazer/openrazer/issues/new/choose

Be sure to mention which keyboard you're using. I can confirm I can't Alt+Tab either on my BlackWidow Chroma. :slightly_smiling_face: 

If it turns out it's intentional (and not a bug) that Alt+Tab is supposed to be disabled, then we can update the frontend here. It would be nice to have the mode configurable though, some day.
