### ISSUE TITLE
Add failsafe for devices lacking get_brightness (Naga Trinity)

### ISSUE THREAD

**Issue by vincenttaglia** [polychromatic/polychromatic#211]
I'm currently reverse engineering the Razer Naga Trinity and from what I have found it doesn't seem like the brightness is a readable variable. If that isn't included, the saved lighting effect is broken (shows up as "???") and the currently set polling rate isn't shown either. Seems like something exited when the get_brightness method wasn't defined.

I think the brightness function would work best if the behavior was something like this:
- Check for get_brightness method
- - If found, get brightness and set the GUI to retrieved value
- - If not found, look for brightness set in local storage.
- - - If found, set brightness to stored value.
- - - If not found, set brightness to 100%, and save that value in storage.
- When brightness is changed and get_brightness method isn't defined, save brightness value to storage.

Also, I think a related bug is when the brightness is changed, it doesn't update the % in the GUI, and an error message shows saying "Failed to set/change brightness..." despite the brightness updating on my mouse. I think this may have to do with get_brightness possibly being used as a check to see if set_brightness worked? My C skills are much better than my Python skills so I had some trouble tracking everything in this repository down, but they are good enough to see there shouldn't be any problems with the Openrazer daemon. I can make a new issue for this bug if you want but I felt like they were related enough to put together.

**Comment by lah7** [comment]
`v0.3.12` is an old codebase, try the [`dev-0.4.0` branch](https://github.com/polychromatic/polychromatic/tree/dev-0.4.0) to see if this is handled better.

I'd recommend using OpenRazer's Python library directly (using `python3` interpreter) to be sure that the Python interface for your new code is working as expected. For example, my Mamba TE mouse:

```python
>>> import openrazer.client
>>> a = openrazer.client.DeviceManager()
>>> b = a.devices[0]   # Assume only Razer mouse plugged in

# Name & Serial
>>> b.name
'Razer Mamba Tournament Edition'
>>> b.serial
dbus.String('PM000000000') # Dedacted

# Get brightness
>>> b.brightness
dbus.Double(100.0)

# Set brightness
>>> b.brightness = 50
>>> b.brightness
dbus.Double(49.8)
>>> float(b.brightness)
49.8

# Get DPI
>>> b.dpi
(1800, 1800)
>>> b.max_dpi
16000

# Set DPI
>>> b.dpi = (800,800)
>>> b.dpi
(800, 800)
```

If any of these are returning wrong data, don't exist, or triggers dbus/daemon/driver issues are problems on the OpenRazer side, likely triggering the red "Failed to set/get [...]" message.

Alternately it could be a problem in Polychromatic's `Controller.update_device_active_options()`, try taking out the `try/except` block in `polychromatic-controller:602-607` to see stacktraces in the terminal:

```diff
            source = command.split("?")[1]
            value = command.split("?")[2]
-            try:
-                common.set_brightness(pref, self.active_device, source, value)
-                self.update_device_active_options()
+            common.set_brightness(pref, self.active_device, source, value)
+            self.update_device_active_options()

-            except Exception as exception:
-                self.print_error(exception, str(_("Failed to set/change brightness for {0}.")).replace("{0}", self.active_device.name))
```

Something like a missing `max_dpi` variable for your device could trigger the error, which would explain why it sets it on the device (`set_brightness`) but has trouble saving that to Polychromatic's internal `devicestate.json` and thus, doesn't get to the code to fully update the GUI.

Other notes:

* Polychromatic needs to consider devices that may have more then one "lighting source" (logo, scroll wheel) but I presume this device just has one (I refer to as `main`).
* OpenRazer [has an open pull request to add effect storage](https://github.com/openrazer/openrazer/pull/888), which may conflict with Polychromatic's internal `devicestate.json` in future.
* Try deleting `~/.config/polychromatic/devicestate.json` 

---

I'm hoping to restart focus on this project again soon (under the [dev-1.0.0 branch](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0)). I'm aiming to turn it into a MVC type of application, so the data sent to/from OpenRazer and GUI will be more abstract in future which will make it easier for adding/debugging devices.

**Comment by lah7** [comment]
I just read your comments in the issue: https://github.com/openrazer/openrazer/issues/541#issuecomment-531448311, so your suggestion of changing how the `get_brightness` works makes sense, but it's a **tricky situation.** 

By design, Polychromatic (v0.3.12) relies on OpenRazer to provide the data, and internally `devicestate.json` to fill in the lack of last used effect "memory" in OpenRazer (until https://github.com/openrazer/openrazer/pull/888). Devices up to now have always been able to tell the driver their brightness value. It's similar to how devices had "hardware effects" but most new Razer devices are dummies, needing software (Synapse) to perform them.

A possible workaround is to have OpenRazer to handle a device's lack of `get_brightness`/`get_dpi` and read/write to a persistent file on the system instead, so Polychromatic/RazerGenie/scripts don't break the 'expected' behaviour.

---

I don't intend to make any releases on the `v0.3.xx` series, as I'd like to focus on the next major version fixing all the issues in the current design.

**Comment by vincenttaglia** [comment]
Thanks for the quick reply!

Sorry, didn't notice there was a newer major release in the works. I'll focus on functionality with the new version.

You hit the nail on the head mentioning the max_dpi method. Adding that fixed the issues I was having with the DPI functionality.

The new version is looking good! The brightness GUI is updated on change even though it can't request the brightness, so that's good. I have yet to try it out with the get_brightness method undefined however. Also, something is wrong with the static color setting. The color picker doesn't show up when the static button is clicked. Trying to track that down now.

**Comment by vincenttaglia** [comment]
Fixed the main issue with [these updates](https://github.com/polychromatic/polychromatic/pull/212/commits/5602e8f5a802281a2e37ea4ceda5dc05c4fe19f9), although there is a currently non-issue bug. If I don't have the Spectrum mode method defined, the mouse isn't recognized. So I do have it defined and clickable, but it just doesn't work. But, the static color feature is working! 

I did have to fix a few issues with depreciated variables and options to get it to run, however.

**Comment by lah7** [comment]
Good to hear, thanks for the feedback. :+1: So, with changes to the `dev-0.4.0` development branch (#212) it sounds like the Naga Trinity is working in frontends **except** for the aforementioned `get_brightness` and `get_dpi` values.  I think it makes sense with this being dealt with in the driver/daemon, but there's no harm in having a failsafe on this side.

I've renamed the issue so it's something for me to consider for new devices going forward.

Since the Razer Naga Trinity is going to break v0.3.12 and this project is developing linearly, your instructions in https://github.com/openrazer/openrazer/issues/541#issuecomment-531525329 are good for users wanting to use this mouse _now_ before OpenRazer or Polychromatic release a new version.

**Comment by vincenttaglia** [comment]
Just get_brightness actually. Get_dpi was only not functioning because max_dpi was not defined.

And sounds good! I think openrazer will take care of the get_brightness issue with the getEffect update, but it isn't a bad idea to have a failsafe.

**Comment by tildearrow** [comment]
> A possible workaround is to have OpenRazer to handle a device's lack of get_brightness/get_dpi and read/write to a persistent file on the system instead,

This is what my pull request aims to do. In my branch get_brightness is no longer handled in the hardware but rather stored as a variable inside OpenRazer.

**Comment by lah7** [comment]
I've been testing https://github.com/openrazer/openrazer/pull/888. There is actually be no need for a "fail safe" on Polychromatic's side. The app only needs to remember what "custom effect" it's playing.

I suppose a "fall safe" is only necessary if Polychromatic were to support non-Razer devices in future.

I've left some feedback on your pull request, @tildearrow.
