### ISSUE TITLE
Packages for Fedora 31 are missing

### ISSUE THREAD

**Issue by ctron** [polychromatic/polychromatic#236]
The build service, providing builds for Fedora only shows Rawhide and 30.

**Comment by lah7** [comment]
@z3ntu maintains the packages for Fedora. I've let him know. Previously the builds were blocked by [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1767403) (now fixed). We should be good to go for Fedora 31 later today. :package:

**Comment by lah7** [comment]
Sorry about this, the bug is still lurking in the OBS system so Fedora 31 builds keep failing... it may be another day or two.  :bug:  :slightly_frowning_face: 

* https://build.opensuse.org/package/show/hardware:razer/polychromatic

In the meantime, if you haven't got Polychromatic installed, you can [download a copy](https://github.com/polychromatic/polychromatic/archive/stable.zip) of the repository, [install dependencies manually](https://polychromatic.app/docs/dependencies/#opensuse) and it'll run from the folder. **Or** maybe the Fedora 30 build will work?

**Comment by lah7** [comment]
Good news! Builds for Fedora 31 are working again. :+1:
