### ISSUE TITLE
Mamba Elite empty menu for main effect

### ISSUE THREAD

**Issue by kblack227** [polychromatic/polychromatic#239]
I can set the mamba elite scroll wheel and logo but can't seem to set the main effect version 0.3.12-stable

**Comment by lah7** [comment]
It's a UI bug in v0.3.12 - there are no **main** effects to set for this device - only **scroll, logo, left** and **right**. v0.3.12 doesn't support left/right.

v0.3.12 won't be receiving updates, as a lot of problems have been fixed in the [unreleased v1.0.0 version](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0) which is blocked/unstable for a couple of reasons.

You could try out the new version early - but effects won't appear in the Controller until https://github.com/openrazer/openrazer/pull/888 is merged, but the new tray applet works well. Turns out this new version also shows an empty "main effects" menu for  this device too which I'll need to fix.

**Comment by lah7** [comment]
[v0.7.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0) has been released, and completely rebuilt the buggy v0.3.12 tray applet. It won't be crashing any more!
