### ISSUE TITLE
Device not recognised

### ISSUE THREAD

**Issue by dragonsKnight5** [polychromatic/polychromatic#248]
I'm getting a message saying the following:

> 
> Device not recognised
> It is possible your razer product is not bound to the driver properly or it is not yet supported

This is strange since it could recognise them when I was still on Fedora 31 before I updated
to Fedora 32

It's not a major issue, I would like to at least have the keyboard backlights turn on though

**Comment by lah7** [comment]
Since you've upgraded to Fedora 32, I would guess your new kernel doesn't have the newer headers package installed for the OpenRazer driver.

Try installing the "headers" package for your kernel, then re-install the OpenRazer package (or via DKMS). Not being familiar with Fedora, I'm unsure of the commands to type.

There's some further troubleshooting guidance here:

* https://github.com/openrazer/openrazer/wiki/Troubleshooting

**Comment by dragonsKnight5** [comment]
it ended up being I was missing the make package, so dkms couldn't run correctly.

I don't know if your part of the openrazer project as well, but would it be possible to add 
the make package to the requirements for the fedora version of the openrazer package

**Comment by lah7** [comment]
@z3ntu looks after OpenRazer's packaging over at the [openSUSE Build Service](https://build.opensuse.org/package/show/hardware:razer/openrazer). I've let him know about the dependency on `make`.

Strangely enough, the `dkms` package on [Arch](https://www.archlinux.org/packages/extra/any/dkms/) and [Ubuntu](https://packages.ubuntu.com/eoan/dkms) depends on `make`, but [Fedora doesn't](https://fedora.pkgs.org/32/fedora-x86_64/dkms-2.8.1-4.20200214git5ca628c.fc32.noarch.rpm.html)?
