### ISSUE TITLE
Please support Razer Blade 15 2018 - en_GB keyboard layout

### ISSUE THREAD

**Issue by danryu** [polychromatic/polychromatic#252]
Hi, Polychromatic is working very nicely on Razer Blade 15 (2018) with Kubuntu 20.04.
Just have a few keys not accessible from the controller config (but I tested they work in https://github.com/openrazer/openrazer/issues/1151).

Could you let me know what you need to make this keys configurable in Polychromatic?
- both Alt keys
- up cursor key
- right Shift key
- Enter key
- F1 key

Thanks....

**Comment by lah7** [comment]
The next version (v1.0.0) will be adding support for multiple device graphics, but for now, v0.3.12 can be "fixed" by manually patching the SVG.

There is a patch in #144 for the Blade Stealth (Late 2016) which might be all you need:

    wget https://raw.githubusercontent.com/polychromatic/polychromatic/8607f48d6776ec3d3c84150b7b2506775590b890/data/img/blackwidow-chroma-keyboard-layout.svg
    sudo cp /usr/share/polychromatic/mapping/blackwidow-chroma-keyboard-layout.svg blackwidow-chroma-keyboard-layout.svg.bak
    sudo cp blackwidow-chroma-keyboard-layout.svg /usr/share/polychromatic/mapping/

If not, you can edit the graphic as seen in https://github.com/polychromatic/polychromatic/issues/11#issuecomment-374028719 using Inkscape.

As a bonus, please run [`step-through-matrix.py`](https://raw.githubusercontent.com/polychromatic/polychromatic/master/tools/step-through-matrix.py) and let me know the mappings. This is just for me to confirm a few thoughts since I have no access to a Razer Blade. :slightly_smiling_face:

**Comment by danryu** [comment]
Thanks, I tried patch #144 and it got me closer, just L Alt and Enter key now unilluminated.
I will hang tight for the 1.0.0 release.

Meanwhile here's the output you requested (btw you still have `razer` instead of `openrazer` as the python lib to imported there, had to work that out)

[step-through-matrix_OUTPUT.txt](https://github.com/polychromatic/polychromatic/files/4673153/step-through-matrix_OUTPUT.txt)

**Comment by lah7** [comment]
Thanks for providing the `step-through-matrix` output. This helped as I have created a new graphic to resemble the design of the Razer Blade (2018) model:

![Screenshot_20210319_184818](https://user-images.githubusercontent.com/13032135/111828768-add05f00-88e3-11eb-837d-f8db0b2c70f0.png)

Since you're on Kubuntu, you can test this by opting to development builds until the final release:

```
sudo add-apt-repository ppa:polychromatic/edge
sudo apt install polychromatic
```
