### ISSUE TITLE
Translation wiki link is dead

### ISSUE THREAD

**Issue by tomers** [polychromatic/polychromatic#253]
In readme the translation howto link is dead.

**Comment by PaoloFalomo** [comment]
i want to translate in italian

**Comment by lah7** [comment]
The translation guide is available at https://polychromatic.app/docs/translations/ (at this time of writing, it's for v0.3.12)

The link in the [README has been fixed in another branch](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0-pyqt5#troubleshooting) for a long time, but it's taking longer then originally planned to get everything merged into `master` that I wouldn't consider a regression in features for users using development/`-git` packages.

There's two codebases, **v0.3.12** (`master`) is frozen and won't see any updates, and the work towards **v1.0.0** (`dev-1.0.0-pyqt5`) isn't fully up-to-date on the locale front. You are welcome to translate earlier knowing there'll be more strings in future and the guide may be out-of-date.

**Comment by PaoloFalomo** [comment]
great! thx i'll start translate asap

**Comment by lah7** [comment]
[The translation guide](https://polychromatic.app/docs/translations/) has been updated according to the newest `master` codebase.
