### ISSUE TITLE
Polychromatic fails to launch on Linux Mint 20

### ISSUE THREAD

**Issue by Bryan9995** [polychromatic/polychromatic#265]
i reinstalled python 3.8 with no luck, it seems to not have fixed the issue. Yesterday I would get the tray icon working, but not it won't even launch, along with the controller.

Last time i had this issue there was a part of a python file i added, I don't know if this would fix it again.

Thanks!

**Comment by lah7** [comment]
Sorry, I was originally unclear in my original response (https://github.com/openrazer/openrazer/issues/1200). I meant to say, reinstall the `polychromatic` package since the failure to launch is caused by a change in Python 3.8 (#245)

If you go into **Software Sources**, are both OpenRazer and Polychromatic's PPAs enabled?

![Screenshot_20200716_160757](https://user-images.githubusercontent.com/13032135/87688152-863a5d00-c77e-11ea-81b6-e883f0c32446.png)

(It should definitely read `focal`, the codename for Ubuntu 20.04)

It should then just be a matter of re-installing the package:

    sudo apt update
    sudo apt remove polychromatic
    sudo apt install polychromatic

I just double checked and confirm it is working in Linux Mint 20.

**Comment by Bryan9995** [comment]
No, the fault is all mine. I assumed i needed to make a new thread since the one seemed to be closed, and I didn't want to be a bother.

As for the issue, I tried your ppa's and re-installing the package and it seems to have not fixed the issue. I did get a bunch of updates after installing it however. So I would hope that it's getting somewhere.

Thanks and sorry for the trouble.

**Comment by lah7** [comment]
Hmm, what's the output when you run it in the terminal?

    polychromatic-controller -v
    polychromatic-tray-applet -v

Also, just to be sure, what's the output of this:

    apt-cache show polychromatic | grep Version

The version should be `0.3.12-focal6`, just to rule out if the older revision was somehow still installed.

**Comment by Bryan9995** [comment]
Sure thing.

**For plychromatic-controller -v:**  
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 26, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'

**for pokychromatic-tray-applet -v:**
Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'


**and for apt-cache show polychromatic | grep Version:** Version: 0.3.12-focal6

i assume the issue lines up with the first two lines.

**Comment by lah7** [comment]
Thanks. It looks like your Python installation can't find the modules, which might have got messed up as a result of (re-)installing Python as you mentioned earlier. What commands did you use exactly?

_(:bulb: Protip: Type `history` in the Terminal)_

----

The packages for those missing modules are `python3-distro` and `python3-gi`, but I'll take a bet they are _installed_ (since they're dependencies), so likely your PYTHONPATH isn't picking them up.

The output of this:

    python3 -c "import sys; print(sys.path)"

Should read:

> ['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.8/dist-packages']

And the output of this:

    which python3

Should be:

    /usr/bin/python3

**Comment by Bryan9995** [comment]
So for your first question, Some of my most recent (and failed) attempts to fix the python issue were some lines as follows:
 1328  sudo modprobe razerkbd
 1329  openrazer -daemon -Fv
 1330  openrazer-daemon -Fv
 1331  sudo gpasswd -a $USER plugdev
 1337  sudo apt install python 3.8
 1338  sudo apt install python
 1339  sudo apt install pythonsudo apt update
 1340  sudo apt install software-properties-common
 1341  sudo add-apt-repository ppa:deadsnakes/ppa
 1342  sudo apt install python3.8
 1343  sudo apt update
 1344  python3.8 --version
 1345  sudo apt install --reinstall polychromatic
 1346  sudo apt update
 1347  sudo apt remove polychromatic 
 1348  sudo apt install polychromatic 
 1349  sudo apt install --reinstall polychromatic
 1350  sudo apt update
 1351  sudo apt remove polychromatic
 1352  sudo apt update
 1353  sudo apt install polychromatic
 1354  sudo apt upgrade
 1357  polychromatic-controller -v
 1358  polychromatic-tray-applet -v
 1359  apt-cache show polychromatic | grep Version
 1360  history
**I removed some lines obviously because many of them were messing with my VPN in between and such**



As for the other line, it seems that's where the issue is:


'python3 -c "import sys; `print(sys.path)":'
['', '/usr/local/lib/python37.zip', '/usr/local/lib/python3.7', '/usr/local/lib/python3.7/lib-dynload', '/home/brett/.local/lib/python3.7/site-packages', '/usr/local/lib/python3.7/site-packages']


'which python3'
/usr/local/bin/python3

**Comment by lah7** [comment]
> 1341 sudo add-apt-repository ppa:deadsnakes/ppa
> 1342 sudo apt install python3.8

> /usr/local/bin/python3
> ['', '/usr/local/lib/python37.zip' .....

I figured this is the case. There's a custom installation of Python (in `/usr/local`) sitting on top of the system. I'd recommend removing this - since it will interfere with other Python apps (like `openrazer-daemon`) too.

Presumably, if Python 3.7 came from this PPA (maybe before the upgrade?), then this might be sufficient:

    sudo apt install ppa-purge
    sudo ppa-purge deadsnakes

:warning: **Be careful** with this - removing the wrong Python may end up taking out lots of system packages!

Another option is to just erase the relevant files in `/usr/local` if Python 3.7 wasn't actually installed as a package:

    sudo rm /usr/local/bin/python3
    sudo rm -rf /usr/local/lib/python3.7/

Then restart the Terminal and check the paths are correct.

**Comment by Bryan9995** [comment]
Your second command did it, Removing the old python packages fixed it, I suppose since 3.8 was the one being run instead of the proper 3.8?

Anyways, Thanks for your help and your time. It means a lot.

**Comment by lah7** [comment]
Glad it's fixed! :+1:

If you'd like to know more about `/usr/local` , take a look here:

* https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html

Not sure if it was a package installing there, but if it's still installed and updates in future, it may come around to bite.
