### ISSUE TITLE
Split Controller and Tray Applet packages

### ISSUE THREAD

**Issue by ifohancroft** [polychromatic/polychromatic#273]
It would clean and streamline things up if you can merge the controller and tray applet into a single Polychromatic app, so the app itself shows in the tray. Being able to choose from the Controller's settings, whether you want it to always show a tray icon or only when minimized or to minimize or close to tray, while the tray icon will have the same options as now.

**Comment by lah7** [comment]
Thanks for the feedback. I see where you're coming from, however it is by design to keep the tray **applet** separate, rather then become a tray **icon** for the main application. The Controller uses at least twice the memory footprint then the tray applet, so running in the background "minimized to tray" may waste RAM when it's not expected to be in use.

v1.0.0 (currently WIP in the [`dev-1.0.0-pyqt5` branch](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0-pyqt5)) is making some adjustments to bridge the UX together:

* The tray applet will be enabled/disabled via the Controller. (https://github.com/polychromatic/polychromatic/issues/191#issuecomment-450910889)
* There will only be one desktop launcher (rather then the current two).
* The tray applet no longer shows a device's current status.

There doesn't seem to be much benefit merging codebases since the two use different toolkits. The Controller is now PyQt5, and the Tray Applet uses AppIndicator/GTK Status Icon.

A "meet in the middle" solution could be to click the tray applet to open the Controller (bypassing the applet's menu), which can be done in future by choosing the "GTK Status Icon" toolkit. Otherwise, I don't think it's necessary as most desktop environments allow you to pin applications to a panel, and there's external tools if you prefer certain applications to minimize to tray.

**Comment by ifohancroft** [comment]
Ah! I get it! The tray applet is to sit on its own. Thanks for taking the time to explain!
Currently, can the tray applet be built on its own or the controller on its one? As in compile just one of them?
I love the idea for v1 but maybe it's worth still keeping the tray applet as a completely separate software in another repo instead of it dissapearing in v1 if I understood the idea correctly.

P.S. Yeah, maybe it's worth separating them in different repos if each can be built on its own

**Comment by lah7** [comment]
I have wondered in the past about splitting **repos**, but I think it complicates things (duplicate build systems, adds more time to develop, history may be out of sync). 

Components are shared between the Controller, Tray Applet and new CLI, so one can function without the other. At the moment, I need to update the new packaging for v1.0.0 (and merge it to `master`), so I'll happily provide options to _compile_ modularly.

Splitting up the **packages** may be on the cards, so a user can install just what they want. E.g. users who don't need the Controller for editing custom effects, won't need Qt dependencies.

* `polychromatic` (meta, install everything)
* `python3-polychromatic` (data files)
* `polychromatic-tray-applet`
* `polychromatic-qt`
* `polychromatic-cli`
