### ISSUE TITLE
Cannot import name "linux_distribution" from platform

### ISSUE THREAD

**Issue by Sc0rp10n2000** [polychromatic/polychromatic#277]
I'm having an issue while trying to run polychromatic. I get this from python.

`Traceback (most recent call last):
  File "./polychromatic-controller", line 37, in <module>
    from platform import linux_distribution
ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/lib/python3.8/platform.py)`

Running as sudo doesn't work either.

**Comment by lah7** [comment]
Which distro? Did you install using a package or clone the repository?

If the latter, please try the [`stable-python38`](https://github.com/polychromatic/polychromatic/tree/stable-python38) branch which addresses this issue.

    git checkout -b stable-python38

**Comment by Sc0rp10n2000** [comment]
Kali Linux 2020.3. Cloned repository. I already changed to stable-python38 branch and I'm getting the same error.

**Comment by lah7** [comment]
Ah, I believe the `git checkout` command won't work since your local clone may not have all the branches. My bad.

I just checked in the Kali Linux 2020.3 live session - the application works by cloning and specifying the branch:

    git clone https://github.com/polychromatic/polychromatic.git -b stable-python38

By the way, since Kali Linux is based on Debian, [adding the repository](https://polychromatic.app/download/debian/) would ensure the package stays up-to-date. :slightly_smiling_face:

**Comment by Sc0rp10n2000** [comment]
Thanks, now it works, but I found out that my Razer blade 15 base model with intel i7-10 gen is not supported. Is there any info about support soon?

**Comment by lah7** [comment]
It looks like support for your model has been requested: https://github.com/openrazer/openrazer/issues/1150

There is a pull request for it too that's wanting testers: https://github.com/openrazer/openrazer/pull/1171
