### ISSUE TITLE
DPI resetting every time I restart my PC - Razer Abyssus Essential

### ISSUE THREAD

**Issue by Psychotechnopath** [polychromatic/polychromatic#278]
Every time I restart my PC, the settings of my Razer Abyssus Essential reset to 1800 DPI (While I always select 1500 DPI). If you need any additional information, let me know I can provide it.

**Comment by lah7** [comment]
In a future update, you'll be able to create a _preset_ and configure the mouse's settings for when you log on.

As a workaround for now, you can create a Python script that interfaces directly to OpenRazer - write this to a text file and add it to your desktop environment's **"Start-up Applications"**:

```
#!/usr/bin/python3
import openrazer.client as rclient
a = rclient.DeviceManager().devices
for device in a:
    if device.type == "mouse":
        device.dpi = (1500,1500)
```

:point_up: Make sure to right click the file and "mark as executable".

**Comment by lah7** [comment]
This should no longer be a problem since OpenRazer has had a persistence feature for years. `openrazer-daemon` will apply the DPI from last time without needing a custom Python script to run at start-up.

However, Polychromatic providing a _presets_ functionality would still be a nice thing in the future, in case we'd like the DPI to always be the "reset" to a fresh value each time.
