### ISSUE TITLE
Device Not Recognised

### ISSUE THREAD

**Issue by shadow-sigyn** [polychromatic/polychromatic#279]
Hi!

Since I upgraded my kernel from 4.19 to 5.7.0 none of openrazer software recognises my keyboard.
I am using Debian 10.
Razer device that I have connected: Razer Blackwidow Chroma Stealth

If I try to `sudo journalctl -b | grep -i razer_mount`
I am getting:
```
Sep 04 18:18:55 debian razer_mount[431]: Driver razerkbd
Sep 04 18:18:55 debian razer_mount[439]: Device_ID 0003:1532:0203.0006
Sep 04 18:18:55 debian razer_mount[448]: Modprobing razerkbd
Sep 04 18:18:55 debian systemd-udevd[335]: Process 'razer_mount razerkbd 0003:1532:0203.0006' failed with exit code 1.
Sep 04 18:18:55 debian razer_mount[641]: Driver razerkbd
Sep 04 18:18:55 debian razer_mount[644]: Device_ID 0003:1532:0203.0005
Sep 04 18:18:55 debian razer_mount[645]: Driver razerkbd
Sep 04 18:18:55 debian razer_mount[646]: Modprobing razerkbd
Sep 04 18:18:55 debian razer_mount[648]: Device_ID 0003:1532:0203.0004
Sep 04 18:18:55 debian razer_mount[650]: Modprobing razerkbd
Sep 04 18:18:55 debian systemd-udevd[373]: Process 'razer_mount razerkbd 0003:1532:0203.0005' failed with exit code 1.
Sep 04 18:18:55 debian systemd-udevd[596]: Process 'razer_mount razerkbd 0003:1532:0203.0004' failed with exit code 1.
```
I am not sure what changed during kernel update... (or maybe something else caused it and I don't know what) I have reinstalled openrazer drivers and polychromatic as well as genie and razer commander when it stopped working, but it did not help. None of them are seeing the keyboard.

Could you please help?

**Comment by lah7** [comment]
Hi, it looks like the driver hasn't rebuilt properly (DKMS is responsible for this), so none of the applications will work until the driver is fixed and can be probed.

Try rebuilding the driver and post the results:

    sudo dkms remove openrazer-driver/2.8.0 --all
    sudo dkms install openrazer-driver/2.8.0

Make sure you do have the correct `linux-headers-xxx` package installed matching your kernel version.

See also: https://github.com/openrazer/openrazer/issues/1205

---

Asking on the OpenRazer repository would yield better support, since this repository has nothing to do with the OpenRazer driver:

* https://github.com/openrazer/openrazer/issues

**Comment by shadow-sigyn** [comment]
Thank you a lot @lah7 ! That was it. After following your advice and restarting, my keyboard got recognised with no other issues.

**Comment by lah7** [comment]
Glad to hear! :+1: Normally updating the kernel package should rebuild the module, but it seems it didn't in this case (maybe a one-off hiccup, or there's a bug the Debian packaging somewhere)
