### ISSUE TITLE
Ubuntu packages: missing python3-distro dependency

### ISSUE THREAD

**Issue by z3ntu** [polychromatic/polychromatic#289]
See 

https://github.com/openrazer/openrazer/issues/1291#issuecomment-708375328

https://packages.ubuntu.com/bionic/python3-distro

edit: or not..?

**Comment by lah7** [comment]
Thanks for noting! Technically that dependency is missing for v0.3.12 packages, though on all Ubuntu's I've tried (including Pop_OS! and elementaryOS), it is already installed.

The new Polychromatic codebase no longer needs the `distro` module. I'd like to avoid touching the v0.3.12 packages (mainly, because users may be using patched copies) so I'll close this issue.
