### ISSUE TITLE
Link in the ToC for Installation leads to the wrong page.

### ISSUE THREAD

**Issue by kygwang** [polychromatic/polychromatic#292]
### Details about the problem

When entering the repo, the user will click on the Installation (see red box) to get more instructions. But instead it links to a different page that asks the user to click on another link. 

![image](https://user-images.githubusercontent.com/8772559/96506652-019c2680-1226-11eb-9c46-d9e5017c8b23.png)

### Operating System / Desktop Environment
Linux Mint 19

**Comment by lah7** [comment]
I think you may have raised this issue on the wrong repo - this is [Polychromatic](https://github.com/polychromatic/polychromatic), a frontend that works with [OpenRazer](https://github.com/openrazer/openrazer) - there isn't a wiki tab nor a link to that page in this repo.

I think OpenRazer kept this page because of legacy links (o prevent link rot), though it has been 2 years so it could be time to drop the link.
