### ISSUE TITLE
Razer Naga; add numpad colors?

### ISSUE THREAD

**Issue by Asitis** [polychromatic/polychromatic#310]
First of all, thank you so much for this! I figured I was never going to get a decent working driver for my Razer Naga mouse on Ubuntu :D The main reason I wanted this is because Razer doesn't sync it's color-profiles to their devices so I was stuck with a default Spectrum rainbow RGB.

This app allows me to change the scroll-wheel and logo RGB lighting just fine, but the Razer Naga has a numpad on the side, and there is no option in the app to set that one, so that will always stay in rainbow-puke mode. I believe it wouldn't be that hard to add it to the UI (?). If there is anything I can do to contribute, let me know!

Sidenote: I have a Razer Naga Left-Handed edition, but I figure this case is the same for both right- and left-handed.

**Comment by lah7** [comment]
I'm glad you like the app! The next generation of the software might bring you more luck.

I would guess you're using v0.3.12 or "stable" version. Try running the `master` branch ([install the new dependencies](https://polychromatic.app/docs/dependencies/), and clone this repo) and see if there's options for the base "mouse" in addition to logo and scroll wheel.

If not, since [your mouse has a "matrix"](https://github.com/openrazer/openrazer/commit/1194b01160f1df9d87be8aeeba454e9e96d14201#diff-f1c965afb06a18c9efce941c7dc3231c2d2588f9376396025590ebbf88566505R1924), this sounds like they might be the individual LEDs that light up the ring side of the mouse. In the new version:

* Choose "Device Info" → "Inspect Matrix" and confirm if the grid lights up the numpad.
* Try the new "effects" feature to create a sequence effect.

The `master` branch is still a work in progress, so bugs expected. If creating an effect lets you light up the numpad, then you could be the first to create a new SVG graphic in the new format to visually represent them - I haven't documented this yet, but can provide pointers.

**Comment by Asitis** [comment]
Thanks for the quick reply! I changed to the daily repository and installed from there but it still installs the stable version. Am I doing something wrong?

**Comment by lah7** [comment]
Nothing wrong on your end, that repository is still on v0.3.12. In hindsight, it doesn't make sense to call it `daily` since I've been treating it as a "semi-stable" for beta testing. I originally wanted to push new packages to `daily` when the "Application Profiles" feature in v0.3.12 for keyboards is fully replaced (See also https://github.com/polychromatic/polychromatic/issues/263). 

I'm going to make some updates to the PPAs - deprecate `daily` and introduce a `edge` (master) and `testing` PPA. If you prefer to use packages, switch `daily` for `edge` using **Software & Updates** and give me a few hours to get it packaged/tested. Otherwise, you can just run the software straight from the repository:

    sudo apt install git python3-colorama python3-colour python3-setproctitle imagemagick python3-requests python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtwebengine gir1.2-appindicator3-0.1 sassc
    git clone https://github.com/polychromatic/polychromatic.git
    cd polychromatic
    ./polychromatic-controller-dev

**Comment by lah7** [comment]
It turns out the _cutting edge_ is temporarily broken on Ubuntu 20.04 (The Controller won't start due to minor changes in Qt 5.12). Tomorrow would be a better opportunity to test this on your Razer Naga mouse.

**Comment by Asitis** [comment]
@lah7 You sir, are a genius! It took me a while to get around to this, but I just installed the other branch, and the program works effortlessly! It recognized the numpad as "right side" (so I'd believe for right-handed mice it be "left side"). Gets picked up great by the Matrix and I'm able to manage all lights on it now :D
