### ISSUE TITLE
FN+volume keys

### ISSUE THREAD

**Issue by green-butterfly** [polychromatic/polychromatic#316]
**Details about the problem**
After polychromatic installation, the vol keys stopped working (including the mute key).
Before that it works without any issues.

**Some reporting tips**
There is no any crashes - polychromatic is stable.
The entire installation process was completed successfully. 

**Mention the steps to reproduce the issue**
```
sudo apt install software-properties-gtk
sudo add-apt-repository ppa:openrazer/stable
sudo apt update
sudo apt install openrazer-meta

sudo add-apt-repository ppa:polychromatic/stable
sudo apt update
sudo apt install polychromatic
```

**Operating System / Desktop Environment**
PC = Desktop PC (asus motherboard)
OS = Ubuntu 20.04.02 LTS
Kernel = 5.4.0-66-generic
Environment = Gnome 3.36.8
OS language = ENG

**Affected Devices**
Razer Blackwidow 2019

**Comment by lah7** [comment]
It's no fault of Polychromatic, but rather, the OpenRazer driver.

I believe this has been fixed by https://github.com/openrazer/openrazer/pull/1363, but there hasn't been a new OpenRazer release with the fix yet. Please try the "daily" OpenRazer builds and restart:

```
sudo add-apt-repository ppa:openrazer/daily
sudo apt update
sudo apt install openrazer-meta
```

(If you don't want constant updates, you can remove the repository afterwards and keep `ppa:openrazer/stable`)

There's a similar issue for Oranta Chroma V2 - https://github.com/openrazer/openrazer/issues/1398 - which might be related, but has no solution yet.

**Comment by green-butterfly** [comment]
Thanks.
I just got the openrazer/stable updates.

The FN+volume keys back work :-)

**Comment by green-butterfly** [comment]
Thanks.
Just got the openrazer/stable updates.

Now it works :-)
