### ISSUE TITLE
Wrong keys linked for Razer BlackWidow Elite

### ISSUE THREAD

**Issue by antarean** [polychromatic/polychromatic#325]
Hi,
There are 2 keys wrongly linked in the device-graphic for the Razer BlackWidow Elite:
1) "Backslash" key ( \ ) should be linked to 14,2 instead of 13,3
2) "Spacebar" key (   ) should be linked to 6,5 instead of 7,5

I have attached a fixed "blackwidow_elite_en_US.svg" file.

[blackwidow_elite_en_US.svg.gz](https://github.com/polychromatic/polychromatic/files/6419251/blackwidow_elite_en_US.svg.gz)

**Comment by lah7** [comment]
Thanks. I'm blind folded for this device since I don't own one 🙈  It was contributed by @beranat in #313 which I presume was correct for his device model.

I would like to wait for further feedback before integrating the changes. 

What's your device's firmware version (under "Device Info")? Unless the original graphic genuinely had the wrong positions, I wonder if different firmware versions could cause differences.

**Comment by beranat** [comment]
Dear @lah7, @antarean is absolutely right the layout has described issues, and scan codes - no.

**Comment by antarean** [comment]
Firmware version = v1.0
To set the colours correctly for the 2 listed keys, I had to go into the grid-display.

If there is a new firmware (and documented method to upgrade safely), please let me know.

**Comment by lah7** [comment]
Thanks @beranat for confirming. :+1: 

Committed @antarean's corrections as a69af5a, thanks again!
