### ISSUE TITLE
[v0.3.12] Static color not changing

### ISSUE THREAD

**Issue by Z4cki** [polychromatic/polychromatic#327]
### Details about the problem

I cannot change the static color of my keyboard. Other effects work fine, but static is refusing to let me change the colour. Its either white or red, but when i click on one of the pre-shown colors, it wont change. Same issue when choosing a custom colour, the (i would called the current-color-field) changes to e.g. blue, but the keyboard doesnt accept the changes

**Comment by lah7** [comment]
Which version of Polychromatic are you using?

----

Let's try changing the colour directly, to find out if it's a fault with the application or OpenRazer (which processes this request).

This command uses the OpenRazer Python library directly - this will set the first device `[0]` to static blue `(0, 0, 255)`:

    python3 -c "import openrazer.client; openrazer.client.DeviceManager().devices[0].fx.static(0, 0, 255)"

If you have multiple Razer devices, you'll need to increment `[0]` → `[1]` accordingly.

Do any errors appear? If it still doesn't work, check the kernel log if OpenRazer's driver complains: 

    dmesg | tail

**Comment by Z4cki** [comment]
The command does work. I managed to change the colour in the application but its inconsistent. It sometimes responses to a selected colour, but more often it doesnt. Also after changing the colour via your mentioned command, polychromatic shows the wrong colour in the overview.

![Bildschirmfoto vom 2021-05-12 13-29-40](https://user-images.githubusercontent.com/76256484/117968222-3f79ad00-b326-11eb-8725-75fe53b6c5be.png)
Current colour is blue.   
   
Using version 0.3.12-stable

**Comment by lah7** [comment]
Good to know it's just v0.3.12. This version is quite old and I may vaguely know what the inconsistency is  - it's to do with how it processes button clicks. No problem with OpenRazer or hardware. This is fixed in the latest code.

The "wrong colour" when setting it outside of Polychromatic is expected with v0.3.12 too, also addressed in the latest code.

---

Try **v0.6.0** instead - it doesn't have a "beta" tag yet but the currently developed features will be stable for your keyboard.

    sudo add-apt-repository ppa:polychromatic/edge
    sudo apt install polychromatic

They'll be package updates whenever there's new changes in `edge`, so if you'd prefer to install v0.6.0 today then only update again for the final release, delete the `polychromatic/edge` PPA via **Software & Updates** → **Other Software** tab.

Just a note, the :de: German translation in v0.6.0 will be incomplete.

**Comment by Z4cki** [comment]
Okay that works beautifully. I used the 'testing' PPA in 20.04, and that's why i had that issue before as well.

If i can help with the translation, hit me up.

**Comment by lah7** [comment]
I still want to consolidate a few loose ends before marking it ready for beta `testing`.

Feel free to fill in the blanks for translations - https://docs.polychromatic.app/translations/ 🗨️
