### ISSUE TITLE
Can't create new effects for Naga Trinity, old Blackwidow

### ISSUE THREAD

**Issue by emersonrp** [polychromatic/polychromatic#349]
### Details about the problem

I have a BlackWidow Ultimate 2013 (old green/brightness-only), Naga Trinity, Goliathus Extended mousepad, and Tartarus Pro attached.  When I poke the "New Effect" button, only the Goliathus is available in the "Device" picker.

The Tartarus Pro isn't yet supported by Openrazer so I don't expect it to show up, but I'd expect to see at least the Naga Trinity, and possibly the BlackWidow in the picker.  As it is, I can only create effects for the Goliathus.

### Operating System / Desktop Environment / Version(s)
Manjaro Linux / KDE
Polychromatic 0.7.0
Openrazer 3.1.0

### Affected Devices
Naga Trinity
BlackWidow Ultimate 2013

**Comment by lah7** [comment]
Device issues would be OpenRazer's territory, but I can give some pointers.

From a quick look, I can already spot a missing variable for the BlackWidow Ultimate 2013, which doesn't have a `HAS_MATRIX = True` variable:

https://github.com/openrazer/openrazer/blob/dcdc92abcaf9ba91e38ea4dbddf552d49b150b50/daemon/openrazer_daemon/hardware/keyboards.py#L331-L344

A quick test on your system would be to edit this file (as root):

    /usr/lib/python3.9/site-packages/openrazer_daemon/hardware/keyboards.py

Add the line `HAS_MATRIX = True` :
```diff
class RazerBlackWidowUltimate2013(_MacroKeyboard):
    ...
    USB_VID = 0x1532
    USB_PID = 0x011A
    DEDICATED_MACRO_KEYS = True
+   HAS_MATRIX = True
    MATRIX_DIMS = [6, 22]
```

Then restart the daemon (in Polychromatic: Tools → OpenRazer). If this works, perfect! Make a pull request on OpenRazer's repository to fix it for other users.

If it doesn't, see below.

---

Likewise, the Naga Trinity should have a matrix too, but it was turned off because the code in the driver was incorrect and threw errors during automated tests (https://github.com/openrazer/openrazer/issues/1252 and https://github.com/openrazer/openrazer/pull/1305)

https://github.com/openrazer/openrazer/blob/dcdc92abcaf9ba91e38ea4dbddf552d49b150b50/daemon/openrazer_daemon/hardware/mouse.py#L940-L952

I'm not entirely sure where in the driver, but there are `case` statements that use the correct "matrix" protocol depending on the device. The Naga Trinity (and some others) have the wrong one. I would suggest opening the issue on OpenRazer's repository for better guidance.

**Comment by emersonrp** [comment]
Awesome, thanks for the pointers.  I'll tinker with this and take it up over in openrazer.
