### ISSUE TITLE
Meson options?

### ISSUE THREAD

**Issue by BlueManCZ** [polychromatic/polychromatic#362]
I'm just curious if there are any compilation options for the project but I didn't find a `meson_options.txt` file. Was it dropped because it was no longer useful?

https://github.com/polychromatic/polychromatic/blob/2b2206a7e884511045e6cda5c2830b935aafb97d/debian/copyright#L26

**Comment by lah7** [comment]
For a short while during a long development cycle, the ability to selective "build" certain components was possible using meson: 8db8028f8b2ee404e7c2b4169937f4672d120fd4. I forgot the exact `meson` command, but there was a parameter to set the options or [by editing that file](https://github.com/polychromatic/polychromatic/commit/8db8028f8b2ee404e7c2b4169937f4672d120fd4#diff-76ea9078099f2ee8cc0e760a874dd153f225ba16ad10375c24ab6cd53518f3c4).

Later in 55863452de8b842b749072130fc8350f60f37aef, I decided that the "split" packaging will happen on a per-distro basis (mainly for Debian/Ubuntu) It's easier to maintain, and prevents the mistake of missing new files because meson required each file to be explicitly stated (wildcards are not supported).

😟 Before: 

https://github.com/polychromatic/polychromatic/blob/8db8028f8b2ee404e7c2b4169937f4672d120fd4/meson.build#L36-L43

🙂 Now: 

https://github.com/polychromatic/polychromatic/blob/97ce8a91224c672f4038edd54e89d8f886bb0d1c/meson.build#L44
https://github.com/polychromatic/polychromatic/blob/97ce8a91224c672f4038edd54e89d8f886bb0d1c/debian/polychromatic-controller.install#L7-L8
https://github.com/polychromatic/polychromatic/blob/97ce8a91224c672f4038edd54e89d8f886bb0d1c/debian/polychromatic-common.install#L5-L7

For the most part, any one wanting to hack on the code should just run it directly from the repository since most of the project is interpreted (Python), [making sure the dependencies installed](https://docs.polychromatic.app/dependencies/) (or have the software installed via a package manager already). `meson` is best used for packaging or custom installation requirements.

Thanks for bringing that `meson_options.txt` to attention. I'll remove its reference, and also [update the "manual build instructions" page](https://polychromatic.app/download/manual/) since it's a bit misleading.

**Comment by BlueManCZ** [comment]
I get it. It is always a little tricky with Python projects and meson. So every user has basically the same package, no matter what? I asked because I'm used to large [`meson_options.txt`](https://github.com/pulseaudio/pulseaudio/blob/master/meson_options.txt) files in big projects, where everyone can specify exactly what they want and what they don't want. Even if it contains for example only the option to enable or disable installing of man pages to the system. Users on Gentoo love free choice. It goes hand in hand with [Gentoo USE flags](https://devmanual.gentoo.org/general-concepts/use-flags/index.html) feature.

With the current build system, how can I build the whole project but for example without a tray applet? It is not mentioned in the [Build Instructions](https://polychromatic.app/download/manual/) you posted. This brings me to the fact, that I was looking for those instructions in the [README.md](https://github.com/polychromatic/polychromatic) file but found nothing. At least a link to the web would be nice.

**Comment by BlueManCZ** [comment]
I completely understand. I will consider contributing there.

I don't think you can fragment Gentoo users more than they [already are](https://gpo.zugaina.org/Overlays). :smile:
