### ISSUE TITLE
Unable to select certain effects

### ISSUE THREAD

**Issue by miramar-labs** [polychromatic/polychromatic#379]
### Details about the problem

Upon selecting certain effects (eg starlight) an error pops up:

OpenRazer encountered an error processing this request. Try restarting the backend/application. If this message keeps appearing, please report this as a bug on OpenRazer's issue tracker.

STACK TRACE:
Traceback (most recent call last):
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 967, in set_device_state
    rzone.starlight_random(speed)
  File ’/usr/lib/python3/dist-packages/openrazer/client/fx.py’, line 586, in starlight_random
    self._lighting_dbus.setStarlightRandom(time)
  File ’/usr/lib/python3/dist-packages/dbus/proxies.py’, line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File ’/usr/lib/python3/dist-packages/dbus/connection.py’, line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.PermissionError: Traceback (most recent call last):
  File ’/usr/lib/python3/dist-packages/dbus/service.py’, line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File ’/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/chroma_keyboard.py’, line 582, in set_starlight_random_effect
    with open(driver_path, ’wb’) as driver_file:
PermissionError: [Errno 13] Permission denied: ’/sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:0255.0004/matrix_effect_starlight’

Filesystem permissions look ok:
aaron@blade:~$ ls -l /sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:0255.0004/
total 0
-r--r--r-- 1 root plugdev 4096 Nov 14 12:14 country
-rw-rw---- 1 root plugdev 4096 Nov 14 12:14 device_mode
-r--r----- 1 root plugdev 4096 Nov 14 12:14 device_serial
-r--r----- 1 root plugdev 4096 Nov 14 12:14 device_type
lrwxrwxrwx 1 root plugdev    0 Nov 14 12:14 driver -> ../../../../../../../bus/hid/drivers/razerkbd
-r--r----- 1 root plugdev 4096 Nov 14 12:14 firmware_version
drwxr-xr-x 3 root plugdev    0 Nov 14 12:14 hidraw
drwxr-xr-x 3 root plugdev    0 Nov 14 12:14 input
-r--r----- 1 root plugdev 4096 Nov 14 12:14 kbd_layout
-rw-rw---- 1 root plugdev 4096 Nov 14 12:16 matrix_brightness
--w--w---- 1 root plugdev 4096 Nov 14 12:14 matrix_effect_breath
--w--w---- 1 root plugdev 4096 Nov 14 12:14 matrix_effect_none
--w--w---- 1 root plugdev 4096 Nov 14 12:14 matrix_effect_reactive
--w--w---- 1 root plugdev 4096 Nov 14 12:14 matrix_effect_spectrum
--w--w---- 1 root plugdev 4096 Nov 14 12:14 matrix_effect_static
-r--r--r-- 1 root plugdev 4096 Nov 14 12:14 modalias
drwxr-xr-x 2 root plugdev    0 Nov 14 12:14 power
-r--r--r-- 1 root plugdev 4096 Nov 14 12:14 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Nov 14 12:14 subsystem -> ../../../../../../../bus/hid
-rw-rw---- 1 root plugdev 4096 Nov 14 12:14 test
-rw-r--r-- 1 root plugdev 4096 Nov 14 12:14 uevent
-r--r----- 1 root plugdev 4096 Nov 14 12:14 version

Rebooting does NOT resolve the issue

### Operating System / Desktop Environment / Version(s)
Fresh install Ubuntu 20.04 with latest openrazer/polychromatic

PLEASE DO NOT DELETE THIS ISSUE unless a solution has been verified ... (@Luke Horwell)

### Affected Devices

Razer Blade 15 base (early 2021)

**Comment by lah7** [comment]
> Rebooting does NOT resolve the issue
> PLEASE DO NOT DELETE THIS ISSUE unless a solution has been verified ...

**Please DO NOT create duplicate issues across multiple repositories!** This will lead to duplicate efforts and that's unfair. That's why I deleted the issue from this repository in the first place. Of all the days, I am really not in the mood today for poor etiquette. 😠 (Sorry everyone watching via 🔔)

This is not an issue with Polychromatic, it's a problem with the permissions of the OpenRazer driver. Let's continue the troubleshooting over at https://github.com/openrazer/openrazer/issues/1671

**Comment by miramar-labs** [comment]
It's got nothing to do with 'poor etiquette' - I posted in both repositories as it is not clear which side the issue is on .. front end or back end ... you came up with a theory and immediately decided the problem was not on polychromatic's side, without taking the time to verify that - which I went on and did .. and you DELETED the issue! That's not how this works ... you should be grateful that folks such as myself take the time to report these issues in such detail, instead you dismiss the report without doing *your* due diligence...

**Comment by lah7** [comment]
I'm sorry, but this is not up for debate. The error message itself clearly stated where to go:

> OpenRazer encountered an error processing this request. Try restarting the backend/application. If this message keeps appearing, **please report this as a bug on OpenRazer's issue tracker.**

Of the years on working alongside OpenRazer, I can confidently say this is not a front-end issue. It can be "fixed" in one command... (until reboot that is)

Yes, me deleting the original issue was hasty, and you should have got the e-mail notification for it (if you have this enabled). I generally don't delete issues unless necessary, but I consider it **spam** because the issue was created in two places, and like I said, it may lead to duplicate efforts and that's not cool.

I am very grateful for users contributing bug reports and pull requests. but this is a support ticket and there are a lot of folks who forget that this work is provided for free from our own will. Besides, I commented on both, but deleted the copy on this repository, so what is the big deal?

**Comment by lah7** [comment]
**One last thing:** I just realised that you posted the output of the `ls` command above and I missed it when responding again with further advise in https://github.com/openrazer/openrazer/issues/1671 as you said here a reboot did not work. This is exactly why duplicating issues is frowned upon.

I deleted my answers there because they are not helpful. It would seem that your device is reporting a "starlight" effect capability (via the OpenRazer daemon), but it's not implemented in the driver -- possibly not supported by your Blade's firmware. That's a bug. You should post the `ls -l` output in that issue to clarify that `matrix_effect_starlight` is missing and confirm it isn't a permission error.

I'm afraid I'm unwilling to personally help any further. It is unfortunate that we did not make a good first impression.
