### ISSUE TITLE
Doesn't recognize my Mouse Razer Basilik v3

### ISSUE THREAD

**Issue by junierkl** [polychromatic/polychromatic#383]
Hello, Good day to everyone,

I installed this app and I have to say I am really impressed, finally a good GUI controller for Linux, sadly my mouse is not recognized by the app.  it shows Unrecognized 1532:0099, I tried with a different USB port without any luck.

My keyboard the Huntsman Mini works perfectly fine

**Comment by lah7** [comment]
Hi, I'm glad you like it! More good stuff is in the works, including improving what this "unrecognized" means 🔧 

This is happening because your Razer Basilik V3 isn't supported in OpenRazer. There is an issue for it at https://github.com/openrazer/openrazer/issues/1610. It needs [packet captures](https://github.com/openrazer/openrazer/issues/1610#issuecomment-966487898) and/or someone to implement it into the driver and daemon, and then it'll automagically work in Polychromatic after updating your copy of OpenRazer.

I'll close the issue here since there isn't anything we can do in Polychromatic. Keep an eye on https://github.com/openrazer/openrazer/issues/1610 for further updates.
