### ISSUE TITLE
Feature request: distribute Flatpak via Flathub

### ISSUE THREAD

**Issue by Peque** [polychromatic/polychromatic#394]
It would be great to have the software distributed as [Flatpak](https://www.flatpak.org/) via [Flathub](Polychromatic). :blush:

**Comment by xtc0r** [comment]
Any update on this?
I use Fedora Atomic (Bazzite) and would like to use polychromatic. As far as I understand the Fedora atomic I have to use flatpak as the way to install software.

**Comment by lah7** [comment]
As far as I know, Fedora Atomic (and others like SteamOS) have immutable filesystems. Polychromatic **needs** OpenRazer, which requires installing a DKMS driver on the host. Are you able to install OpenRazer just as easily in Fedora Atomic? 

OpenRazer can't be a Flatpak:

> In general Flatpak is best suited for desktop applications and while command line applications also work, it may not be suited in some cases:
>
> * Kernel modules or drivers are non application packages and won’t work inside a Flatpak.
>
> Flatpak also won’t export udev rules or systemd services from the sandbox to the host and requires manual configuration after installing the flatpak package.
>
> — https://docs.flatpak.org/en/latest/introduction.html

So far, I haven't heard of successful OpenRazer installations under SteamOS, so installing this app is useless for as long as OpenRazer 3.x is a DKMS driver.

Right now, I don't have incentive to invest time into a Flatpak since the software is already available for a wide variety of distros in their native package format. I have some other concerns:

* Users will want to press "Install" and it magically just works for their Razer stuff, but it needs manual intervention anyway because of OpenRazer being a driver.
* The sandboxing nature of Flatpak may also break some functionality of this software, like troubleshooting, configuring OpenRazer, theme integration (Qt), and [new features in the future](https://docs.polychromatic.app/roadmap/).

**Comment by razzeee** [comment]
You can use https://flathub.org/apps/xyz.z3ntu.razergenie after installing OpenRazer on the system. You'll get the best of both worlds. There are talks about enbaling flatpaks to ship kernel stuff etc, but it's very early.

**Comment by xtc0r** [comment]
OpenRazer is installed and working. Bazzite OS asks you during the first startop if you want to install it.
I'm using https://flathub.org/apps/xyz.z3ntu.razergenie but it has limited features.
In my case I want that my Razer mouse dock indicates the battery status of my Razer Viper Ultimate battery level via LED coloring. That's a feature the Windows Razer software has. I hoped for polychromatic to provide a similar feature. RazerEngine does not.

**Comment by z3ntu** [comment]
WIP Flatpak manifest: https://github.com/z3ntu/flathub/tree/polychromatic

**Comment by lah7** [comment]
Polychromatic is now [on Flathub!](https://flathub.org/apps/app.polychromatic.controller) Massive thanks to @z3ntu for making this possible!

Please note that Flatpak is more restrictive, so not all our features work seamlessly _(yet)_. See the [Flatpak page on our website](https://polychromatic.app/download/flatpak/) for more details. OpenRazer will still need to be installed on the host as usual.
