### ISSUE TITLE
How to translate Polychromatic in a language already translated and available ? 

### ISSUE THREAD

**Issue by olielvewen** [polychromatic/polychromatic#403]
Hi 

I use a Razer mouse and have just completed an article/blog entry [(here](https://linuxevolution.wordpress.com/2022/02/04/et-si-on-prenait-un-peu-de-polychromatique/)) on your superb and functional software. And at the very end, in my reviews, I lamented that the software was not translated (apart from English) given its age, which was surprising. Looking at the faq, I see everything about translating the app but not how to translate it itself. Also nothing in the issues on this subject.

How do you translate Polychromatic into languages ​​already translated and available?

Can we imagine an automatic translation during the installation or a choice in a QComboBox for example?

Why use gettext and not the way to get QT with QtLinguist?

In any case, thank you for this superb and functional software and especially for the time you have done for this project.

### Operating System / Desktop Environment / Version(s)
Manjaro - kernel 5.15 - Cinnamon/Kde

### Affected Devices
The GUI

**Comment by lah7** [comment]
Thank you for the kind words, I used a translator to have a read through. 👓  I have ideas to improve some of the things you've mentioned, but it will be a while, the to-do list is already long. For battery notifications, you might like the improvements at https://github.com/openrazer/openrazer/pull/1666 that'll be available in the next OpenRazer version (or today with the `openrazer-meta-git` packages) 🙂 

---

> How do you translate Polychromatic into languages ​​already translated and available?

The documentation for ["Translations" under "Updating existing translations"](https://docs.polychromatic.app/translations/#updating-existing-translations) covers the steps at the bottom. It assumes the [repository is already cloned](https://docs.polychromatic.app/translations/#preparing-the-repository). It seems a bit unclear, but I can re-review this page at a later date.

> Can we imagine an automatic translation during the installation or a choice in a QComboBox for example?

The application should automatically use your system's locale. Although just now, it seems there's a bug. It works when you run from the repository folder, but not when installed system-wide (as a package), sorry about that. I'll need to investigate and fix that.

![image](https://user-images.githubusercontent.com/13032135/152607676-634e76c7-d403-445c-a182-5408b2724d6c.png)

The French `fr` translations are out of date, so many sections of the interface will display in English as a fallback.

> Why use gettext and not the way to get QT with QtLinguist?

You can probably use **Qt Linguist** instead of **Poedit** to perform the translation. `gettext` is the chosen library since it [ships alongside Python](https://github.com/python/cpython/blob/3.10/Lib/gettext.py), and has been used before this application switched to PyQt5.

**Comment by lah7** [comment]
The aforementioned bug for translations has been [fixed](https://github.com/polychromatic/polychromatic/commit/da9efb2e3358189c80afecd320f472e185b92abe) for the next release. It's currently in a refactor branch and will automatically close this issue once merged. 👍🏼

**Comment by olielvewen** [comment]
Thank you for the kind words, I used a translator to have a read through. eyeglasses I have ideas to improve some of the things you've mentioned, but it will be a while, the to-do list is already long. For battery notifications, you might like the improvements at openrazer/openrazer#1666 that'll be available in the next OpenRazer version (or today with the openrazer-meta-git packages) slightly\_smiling\_face

Normal, I'm aware than to design a gui is a long race and need a lot time and effort.

It was not the first time than I've written about Polychromatic ([here](https://linuxevolution.wordpress.com/2018/11/23/me-gamer-and-linux-user-impossible-mission-not-exactly-part-2/)) but the project was not alone. I haven't think to take a look at OpenRazer drivers.

    The documentation for "Translations" under "Updating existing translations" covers the steps at the bottom. It assumes the repository is already cloned. It seems a bit unclear, but I can re-review this page at a later date.

Indeed it is not very clear.

     The application should automatically use your system's locale. Although just now, it seems there's a bug. It works when you run from the repository folder, but not when installed system-wide (as a package), sorry about that. I'll need to investigate and fix that

I have Polychromatic on two systems and same issue on the both. And yes, I have installed it with yay like this.

\`\`\`yay -S polychromatic\`\`\`

    The French fr translations are out of date, so many sections of the interface will display in English as a fallback.

Hum, If I have a bit of free time, find the good branche to translate (which one ? under master, perhaps backend\_refactor/ stable ? ) and if I can translate with Qt Linguist, I'll take a look. After, when I translate a software, I like to see the result before. How to perform that ? I'm using PyCharm.

You can probably use Qt Linguist instead of Poedit to perform the translation. gettext is the chosen library since it ships alongside Python, and has been used before this application switched to PyQt5.You can probably use Qt Linguist instead of Poedit to perform the translation. gettext is the chosen library since it ships alongside Python, and has been used before this application switched to PyQt5.

I hope and Great news.

**Comment by lah7** [comment]
Translations are a bit of a cat & mouse race  🐱 🐭  since after the refactor, I'll be implementing new/improved features which would require another translation update. So, it's up to you to start or wait. 

`backend_refactor` would be the most up-to-date to base the translations on, but do bear in mind there's some incomplete changes _(like lack of device images, "Apply to All" menu is empty, Device Info crashes)_ while this refactor is in progress. ⚙️ 🔧 

Since you already have the software installed, you can mostly [run the software straight from the repository folder](https://docs.polychromatic.app/translations/#testing-a-translation) using the `./polychromatic-controller-dev` script.

**Comment by olielvewen** [comment]
> Translations are a bit of a cat & mouse race :cat::mouse:since after the refactor, I'll be implementing new/improved features which would require another translation update. So, it's up to you to start or wait.

Hum, I'll see following my free time. I hope that I won't forget.  

>  backend\_refactor would be the most up-to-date to base the translations on, but do bear in mind there's some incomplete changes _(like lack of device images, "Apply to All" menu is empty, Device Info crashes)_ while this refactor is in progress. :gear::wrench:

Okay. It will depends of the work to do (a lot or not).

> Since you already have the software installed, you can mostly [run the software straight from the repository folder](https://docs.polychromatic.app/translations/#testing-a-translation) using the `./polychromatic-controller-dev` script.

Well not if I'm using the backend\_refactor. Anyway, I must before fork backend\_refactor and translate it (and not testing with my stable/master branch) it doesn't work if they are some differences. No ? I'll check in Pycharm.

**Comment by lah7** [comment]
The `fr_FR` translation is 65% complete, with 212 strings to do. 

There's no hurry, I think translating before a release is due would be more productive.  Do you think a mailing list, or online service like [Weblate](https://weblate.org/en-gb/) would make it easier for interested translators? 🔔 

---

The beauty of Python is that you can run a different version of the software without needing to "install" it. Since the software was installed from the AUR, all the dependencies should be already installed.

The handling of this branch becomes a `git` thing. There's multiple ways to set things up. Let's suppose you fork this repository (top-right of GitHub) and clone your copy locally, you can retrieve this branch and check it out:

```
git remote add upstream https://github.com/polychromatic/polychromatic
git fetch upstream
git checkout backend_refactor
```

First, update the locale templates:

    ./scripts/create-locales.sh

Edit in Qt Linguist, save and then preview:

    ./polychromatic-controller-dev 

You can switch between branches to see the different builds, like so:

    git checkout master
    ./polychromatic-controller-dev 

    git checkout backend_refactor
    ./polychromatic-controller-dev

**Comment by olielvewen** [comment]
> The `fr_FR` translation is 65% complete, with 212 strings to do.

That's all ? That should not give my some problems gobally. I've done worse in the past.

> There's no hurry, I think translating before a release is due would be more productive. Do you think a mailing list, or online service like Weblate would make it easier for interested translators? bell

Okay. 

You have 3 ways to my knowledge to translate an application.  
\- By hand by creating qt files, translating them using tools like qt linguist or poedit and then incorporating the translations into your code  
\- using Launchpad which has a translation platform integrated into the project in the same way as ppa. Personally, I don't know how it works even though I've used it before.  
\- by using translation web platforms like the one you mention or transiflex used by certain projects including HotShot  
  
The latter is certainly the most suitable solution for your project which is quite popular and rightly so. A mailing list? I do not know. A Discord room for the project with a topic for the translation surely. I would prefer a web platform like the one you mention. The simpler it is, the more people there will be. 

A request for help on sites like Phoronix and OMGubuntu would be the right trigger, but for that everything would have to be ready beforehand.

> The handling of this branch becomes a git thing. There's multiple ways to set things up. Let's suppose you fork this repository (top-right of GitHub) and clone your copy locally, you can retrieve this branch and check it out:

  
Thank you for telling me how to fork then update a branch but I already knew how to do it (I play a little with git although badly sometimes and especially punctually) but it is never useless to specify it again. Especially since some who don't know can see your explanations.  
 

> First, update the locale templates:

```
./scripts/create-locales.sh
```

> Edit in Qt Linguist, save and then preview:

```
./polychromatic-controller-dev 
```

Okay.

> You can switch between branches to see the different builds, like so:

```
git checkout master
./polychromatic-controller-dev --locale=fr_FR

git checkout backend_refactor
./polychromatic-controller-dev 


By recovering master, we also recover the other dev branches? It is the only thing that I must know.
```

**Comment by lah7** [comment]
Thanks for your thoughts. I forgot about Launchpad's translations tab, and I've set up Transifex for Ubuntu MATE before.

Personally I prefer the decentralized file-based solution that's currently set up (from a maintainer's point of view). Integrating a web platform is something I might do in future. It's not a priority at the moment but more something to do when the project is feature complete and ready for the masses. 🌍 

> By recovering master, we also recover the other dev branches? It is the only thing that I must know.

I'm not sure what you mean. Switching between these two branches (`master` and `backend_refactor`) while modifying `fr_FR.po` is only possible as the file hasn't changed in both branches.

**Comment by olielvewen** [comment]
> Personally I prefer the decentralized file-based solution that's currently set up (from a maintainer's point of view). Integrating a web platform is something I might do in future. It's not a priority at the moment but more something to do when the project is feature complete and ready for the masses.:earth\_africa:

I think and agree like you.

> I'm not sure what you mean. Switching between these two branches (`master` and `backend_refactor`) while modifying `fr_FR.po` is only possible as the file hasn't changed in both branches.

Sorry, I have not been enough clear. Which branches (`master` or `backend_refactor`) should must translate currently ?

**Comment by lah7** [comment]
I just checked, there's about 11 strings difference, so translating either branch is OK.

`backend_refactor` is newer, but as you preview them in the application, not all features may be fully working (like **Device Info**)

**Comment by olielvewen** [comment]
Okay. I 'll do it soon I have a bit of free time. And I'll check too a way that I've found there are one hour ago checking my personal git notes.

**Comment by olielvewen** [comment]
I have take a look today (not available the 2 others days for personal reasons) and I run into an issue:

```
./scripts/create-locales.sh                        ✔   
which: no intltool-extract in (/home/olivier/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
Command for 'intltool-extract' not found.

Some tools are missing. Please install them and run this script again.
```

I have checked and not found this tool in my package tool on AUR and in international Manjaro forum. I have search gettext (already installed) xgettext (not existing). I'm able to open po files in Qt Linguist but not pot file. A idea ?

**Comment by lah7** [comment]
In Arch, `intltool-extract` is provided by the package `intltool`. `pacman -F` can help discover the package:

```c
$ pacman -F intltool-extract
extra/intltool 0.51.0-6 [installed]
    usr/bin/intltool-extract
```

(The Debian/Ubuntu equivalent is `dpkg -S`, I think)

📝  In future, I'll add the translation packages to the [Dependencies](https://docs.polychromatic.app/dependencies/) docs.

**Comment by olielvewen** [comment]
Hi,

This trick actually allowed me to install the necessary tools. Thanks.

The screenshot below shows that Qt Linguist does not work, so I had to resolve to install Poedit.


In my opinion it will be necessary change the corresponding documentation because it only works if the software has not already been translated. I learned it at my own expense. In fact, it is necessary to translate the existing po file and not the pot file if there is already a current translation.

When I realized it he was too late. so I've retranslated everything (NB: the 607strings !).

**Comment by lah7** [comment]
> The screenshot below shows that Qt Linguist does not work

Looks like the screenshot wasn't uploaded? 📷 

For basic operation, Qt Linguist does work and saves the file correctly. There is no preview under "Sources and Forms"  _(it says "about.ui.h not available")_ but that's a limitation of how the strings are extracted from this application.

---

> In fact, it is necessary to translate the existing po file and not the pot file if there is already a current translation.

This is the expected workflow - edit the PO file or create using the POT. The script takes care of updating both the POT and PO, previously this was manually done. Both files are identical.

I apologise for the unclear documentation. I can see how this can be confusing and isn't presented in a logical order (currently, the "edit an existing" is at the bottom). I'll rewrite that page later today.

**Comment by olielvewen** [comment]
> Looks like the screenshot wasn't uploaded?:camera:

Indeed, I have had some issues with my usual website (its seems to be dead) for sharing images and after I have completely forgotten.

Here the problem that I have had.

\[!\[poly-translation.png\](https://i.postimg.cc/x8sxZ0bR/poly-translation.png)](https://postimg.cc/N2Hk9vD9)

> ![💡](https://fonts.gstatic.com/s/e/notoemoji/14.0/1f4a1/32.png)
> 
> **Tip:**
> 
>  It is possible to change the "base branch" by editing the title of a pull request ^

BTW Thanks for the tip, I was not aware. De rien cela a été un grand plaisir même si j'ai perdu la main.

**Comment by lah7** [comment]
That is strange:

    Unsupported codec: "CHARSET"

Qt Lingust says that for me too when I open the **.pot** file, but **fr_FR.po** opens correctly. 🤷🏼 

---

Anyway, [this issue is set to automatically close](https://github.com/polychromatic/polychromatic/issues/403#issuecomment-1030650313) as soon as the refactoring is completed and is merged into `master`. Any users using `polychromatic-git`  on Manjaro/Arch users will receive the localization fix and updated translation. :+1:

**Comment by olielvewen** [comment]
> Qt Lingust says that for me too when I open the **.pot** file, but **fr\_FR.po** opens correctly. 🤷🏼

Indeed and yes it has been the first time i encountered this error.

> Anyway, this issue is set to automatically close as soon as the refactoring is completed and is merged into master. Any users using polychromatic-git on Manjaro/Arch will receive the localization fix and updated translation. +1

Great news. 

> [I also updated the documentation](https://docs.polychromatic.app/translations/) so it should be clearer for next time.

Perfect. Nice work. Just a precision for the last point ie Commit your changes. Only if you have done the translation in the master branch and how when it has been done in a specific branch ?

**Comment by lah7** [comment]
The `master` branch is where translations should be performed nearly all the time. A specific branch was an exception in this scenario due to the current codebase getting a refactor / clean up.

It is a common practice for developers to keep breaking changes out of the main branch. Packages like  `polychromatic-git` would inherit some breakage. It's only temporary, but needs some more work & time - I should get back to completing this when I get time.

**Comment by olielvewen** [comment]
> The `master` branch is where translations should be performed nearly all the time. A specific branch was an exception in this scenario due to the current codebase getting a refactor / clean up.

Okay

> It is a common practice for developers to keep breaking changes out of the main branch. Packages like polychromatic-git would inherit some breakage. It's only temporary, but needs some more work & time - I should get back to completing this when I get time.

Indeed. Usually, I open a branch in my Dev branch for all and even translations. A good practice for avoiding some errors....from my part sometimes.
