### ISSUE TITLE
The app does not save DPI selection after restart on Ubunut 20.04

### ISSUE THREAD

**Issue by bigcacarouci** [polychromatic/polychromatic#404]
Whenever i set a diferent DPI on Polychromatic app, it works until the next computer restart when it goes back to default settings. How can i start to debug this?

![image](https://user-images.githubusercontent.com/14179412/152640990-f977a07d-316f-4ccf-97ef-df416fe25c65.png)

Ubuntu 20.04
Razer Deathadder 3.5G

**Comment by lah7** [comment]
At the moment, we rely on OpenRazer's persistence feature to restore settings at login, or the hardware. I assume you're running the latest OpenRazer (v3.2.0) from the PPA.

The DeathAdder 3.5G is a bit of an unconventional mouse since it only has one dimension for DPI (X), and only supports specific DPI.  Most other mice support two dimensions (X,Y) and are variable. In the past, there's been bugs with single DPI mice when the wrong Y value was implemented in both projects (#354), but that's been fixed.

Some places to check:

* Daemon's logs for OpenRazer: `~/.local/share/openrazer/logs/razer.log`
* Check the settings and persistence file in `~/.config/openrazer/`

I'm not 100% sure if invalid DPI causes the value to reset to defaults. If that's the case, try turning off persistence in `~/.config/openrazer/razer.conf`. That's assuming the hardware remembers it across reboots, in which case the bug could be `openrazer-daemon`'s handling of fixed DPI mice.

**Comment by bigcacarouci** [comment]
Thanks for the detailed response!. It seams that the ~/.config/openrazer/persistence.conf only has this content and nothing about the DPI. The poll_rate is persistent across restarts so the file itself works correctly.

```
[DeathAdder35G]
poll_rate = 1000
```
I guess if i just set the DPI inside this file, it will be persistent across restarts. Do you have any idea what is the right line to use so i can accomplish this?

**Comment by lah7** [comment]
You could try that, these are the lines for my Mamba TE mouse: 
```
dpi_x = 1800
dpi_y = 1800
```

The Y should be `0`. At least, that's what this software needs to do for it to be accepted. Previously it was erroneously `-1`. It's possible the daemon isn't handling your mouse properly, so it fails to read/write the correct value 🤔 

If that doesn't work, try turning off persistence:
```
[Startup]
restore_persistence = False
```

**Comment by bigcacarouci** [comment]
Thanks, i managed to make it persistent but not in a conventional way.
I tried 
`[Startup]
restore_persistence = False`
in the ~/.config/openrazer/razer.conf file but ~/.config/openrazer/persistence.conf still rewrote after restart
The solution i tried and that finally worked was
In ~/.config/openrazer/persistence.conf i wrote
```
[DeathAdder35G]
poll_rate = 1000
dpi_x = 900
dpi_y = 0
```
and i marked the file ~/.config/openrazer/persistence.conf  as ReadOnly . 
Now the 900 DPI is consistent on all restarts.
Thanks again for the help and keep up the good work.

**Comment by lah7** [comment]
You're welcome, glad it's working! :+1:

For what it's worth, I created an issue for this at https://github.com/openrazer/openrazer/issues/1744 so it can be fixed properly some day.
