### ISSUE TITLE
root user can not see devices, even with sudo -u or runuser

### ISSUE THREAD

**Issue by BaronVonSatchel** [polychromatic/polychromatic#416]
### Details about the problem

My Razer Naga Trinity forgets its settings every time it loses power, e.g. when the computer is restarted or put to sleep. When it comes back on, it resets to the default "cycle through all the colors of the rainbow" effect. There doesn't seem to be a fix in polychromatic right now (going by the answer to #389), so I'm trying to work around it by creating a systemd unit to run polychromatic-cli. But systemd runs as root, which seems to be a problem for polychromatic. The command works if I run it as my normal, non-root user:
```
user@computer:~$ polychromatic-cli -v -d mouse -o static -c FFFFFF
[openrazer] Setting client setting: allow_image_download to 1
[openrazer] Setting client setting: ripple_refresh_rate to 0.05
Loaded 1 backend(s):
 - OpenRazer
[openrazer] Initialising Device Manager...
Successfully executed request.
```
Works as expected!
However, running it as root gives:
```
root@computer:/home/user# polychromatic-cli -v -d mouse -o static -c FFFFFF
Loaded 1 backend(s):
 - OpenRazer
[openrazer] Initialising Device Manager...
No devices connected.
```
OK, so maybe the daemon is running under my user, and I have to run the command as me as well. Here goes:
```
root@computer:/home/user# runuser -u user -- polychromatic-cli -v -d mouse -o static -c FFFFFF
[openrazer] Setting client setting: allow_image_download to 1
[openrazer] Setting client setting: ripple_refresh_rate to 0.05
Loaded 1 backend(s):
 - OpenRazer
[openrazer] Initialising Device Manager...
No devices connected.
```
Slightly different output, it finds my user settings, but still can't detect the device.
I tried the same with `runuser -l user` `runuser -g plugdev` `sudo -u user` and all had the same result.

This may not be a bug in polychromatic or openrazer per se, so much as it's a side effect of how Linux compartmentalizes things for security. Nonetheless, it would be great if I could find a solution to save me from having to manually change my settings in the GUI each time I turn my PC on.

### Operating System / Desktop Environment / Version(s)
Linux Mint 20.2 Cinnamon 64-bit

### Affected Devices
Razer Naga Trinity

**Comment by lah7** [comment]
OpenRazer's daemon isn't designed to run under root. I think the main problem is to do with being unable to access the D-Bus session/system bus from other users and _environments_ (like a systemd service), and _possibly_ race conditions too.

Creating a systemd service is pretty complicated. The startup scenario can be resolved by either:

1. Setting `restore_persistence = True` in `~/.config/openrazer/razer.conf`. This  software feature is supposed to apply the last settings to your device whenever the daemon starts. 

4. Or, add the command to your **Startup Applications**, which runs as soon as you log in:

    In Cinnamon, search for "startup" and open it. Add a "custom command" via the <kbd>+</kbd> button:

    ![Screenshot_20220501_151112](https://user-images.githubusercontent.com/13032135/166149679-181447c5-fdae-4464-8f07-b89bc7a8bd92.png)

    Then add your command there:

    ![Screenshot_20220501_151153](https://user-images.githubusercontent.com/13032135/166149714-bfd77f45-98d7-4bb2-8553-499191a1332f.png)

This definitely works because `openrazer-daemon` user service is set up to start if an application requests it, like Polychromatic. If there's no devices detected, then it might be a race condition - add a delay if so.

This doesn't cover the waking up from sleep. Maybe it's possible to restart `openrazer-daemon` user service after sleep (if option 1)? The alternate might be to see if there's any BIOS settings to prevent USB ports from being fully powered off... or it's possible this mouse might actually just like to reset to spectrum when it's off 🖱️ 

Like you saw in #389, I'd like to make this kind of automation more convenient to manage in future.

**Comment by lah7** [comment]
Closing stale issue.  TL;DR, OpenRazer daemon isn't _designed_ to run as root, due to the D-Bus session bus.
