### ISSUE TITLE
Tray Applet Doesn't Display Submenus Properly

### ISSUE THREAD

**Issue by XGZepto** [polychromatic/polychromatic#434]
### Details about the problem

- When clicking on any dropdown menus (brightness, effects, primary colour, etc.), the options won't appear with only a thin line under the selection.

![image](https://user-images.githubusercontent.com/38270878/189805474-a08c83d1-dd46-49f9-8bb1-372f5f4217a7.png)

### Operating System / Desktop Environment / Version(s)

Reproduced w/ Gnome 42 on Manjaro / PopOS on my Razer Blade 14 (2021).

![image](https://user-images.githubusercontent.com/38270878/189806167-6cfb9e8a-4f91-4d87-8733-46703b15cb03.png)

Applet Render set to AppIndicator3 or Ayatana behaves the same.

**Comment by lah7** [comment]
I couldn't reproduce an empty submenu on stock Ubuntu 22.04 (GNOME 42.2), nor by simulating your device under OpenRazer's "fake" driver. The code appears to be working, so the issue lies with GNOME or the desktop GTK theme for not rendering the submenu properly. Is that the Adwaita theme, or are you using a custom theme?

Even when it works, I'm not too fond of how GNOME presents the tray applet either:

![image](https://user-images.githubusercontent.com/13032135/189832224-faf11d18-587b-4bf9-9931-eed897e03163.png)

**Comment by XGZepto** [comment]
> 

The problem is solved by lowering the scaling factor in gnome settings; anything equal to or more than 175% (running at 2560x1440) results in an empty submenu. (Maybe it's a gnome issue?)

**Comment by lah7** [comment]
Glad there's a solution! Yes, it's a definitely some kind of issue or quirk with GNOME or AppIndicator. There's nothing I can do on the application side.

Possibly the display server could play a role too: **X11** vs **Wayland**. Also, apparently when scaling changes, a log out and re-login might be necessary so apps (and GNOME) render use the new scale correctly. I believe anything between 100-200% is "fractional scaling" which might be considered experimental.
