### ISSUE TITLE
Razer Basilisk v3 RGB lights do not turn off on PC shutdown

### ISSUE THREAD

**Issue by dydzio0614** [polychromatic/polychromatic#444]
### Details about the problem

As in title - I did not mess with polychromatic settings, only adjusted DPI so it's unlikely i messed up something. On PC shutdown RGB is still active, goes away if I replug mouse.

### Operating System / Desktop Environment / Version(s)

Kubuntu 22.04 LTS with latest patches applied

### Affected Devices

Basilisk v3 - the only razer device I have

**Comment by lah7** [comment]
Have you tried a different USB port? Assuming you've got a desktop motherboard, some (or all) of the ports might continue supplying power to the device even though the system is shut down. It's typically a motherboard feature designed to charge other devices. There might be a setting in the BIOS/UEFI to turn it off.

I'd guess that re-plugging works because the mouse power cycled and isn't receiving a signal that it's time to work. Technically, when the OS is running and OpenRazer is installed, the device has to change to a "driver" mode otherwise it's just a generic mouse to Linux.

It's not really Polychromatic's problem, [OpenRazer is responsible](https://github.com/openrazer/openrazer/issues?q=Razer+Basilisk+v3+) for the actual communication to the device. It could be a quirk with this mouse's firmware if it doesn't happen under Razer Synapse on Windows.

**Comment by dydzio0614** [comment]
I confirm that different USB port solved the issue lol
