### ISSUE TITLE
Razer DeathAdder V2 polling rate is not persistent after rebooting

### ISSUE THREAD

**Issue by tur1ngb0x** [polychromatic/polychromatic#447]
### Information
* OS: PopOS 22.04 LTS
  * DE: GNOME 43
  * Display: X11
  * Kernel: 6.0.6-76060006-generic
* Mouse: Razer DeathAdder V2
  * VID:PID: 0084:1532
  * Firmware Version: v1.2
* Polychromatic: 0.7.3 (PPA Jammy)
  * Save Data: 8
  * Python: 3.10.6
  * Qt: 5.15.6
* OpenRazer: 3.5.0 (PPA Jammy)

### Details
* Open Polychromatic GUI, select 125Hz as polling rate, apply, exit.
* Polling rate is set to 125Hz successfully.
* After rebooting, the polling rate changes back to 1000Hz.

```
$ polychromatic-controller -v
Initialising application...
Initialising window...
Initialising troubleshooters...
Opening tab: 0
Initialising backends...
[openrazer] Setting client setting: allow_image_download to 1
[openrazer] Setting client setting: ripple_refresh_rate to 0.05
[openrazer] Initialising Device Manager...
Backends loaded in 0.248s.
Opening tab: 0
[openrazer] Persistence read unnecessary for Razer DeathAdder V2 (Zone: main)
[openrazer] Persistence read unnecessary for Razer DeathAdder V2 (Zone: main)
Setting option 'poll_rate' on Razer DeathAdder V2 (openrazer device 0)
  -> Zone: main | Param: 125 | Colours: []
Request successful
Main window closed, goodbye!
Main window closed, goodbye!
```

**Comment by lah7** [comment]
Polychromatic doesn't have direct control over the persistence of the settings. This would be up to [OpenRazer](https://github.com/openrazer/openrazer).

I have a feeling that this upcoming change should "fix" this issue for your device:

* https://github.com/openrazer/openrazer/pull/1957

You're welcome to test that, or wait until its merged so it can be tested via `ppa:openrazer/daily`. In the meantime, you could see if turning on/off OpenRazer's persistence feature helps:

* https://github.com/openrazer/openrazer/issues/663#issuecomment-1305276628

Closing the issue here as there isn't anything on Polychromatic's side that can resolve this.
