### ISSUE TITLE
Razer Blade 15 Advanced (Early 2022): Setting static color has no effect.

### ISSUE THREAD

**Issue by Weuxel** [polychromatic/polychromatic#458]
### Details about the problem

Setting a static color has no effect. The color of the keyboard always defaults to green.
Setting a color on other effects like breath or ripple is working.

### Operating System / Desktop Environment / Version(s)

Xubuntu 22.10
XFCE 4.17
Kernel 6.0.9
Polychromatic 0.8.0
Python 3.10.7
Qt 5.15.7
OpenRazer 3.5.1
D-Bus 1.14.0
DKMS 3.0.6

### Affected Devices

Razer Blade 15 Advanced (Early 2022)
VID:PID 1532:028A

**Comment by lah7** [comment]
I've opened an issue for OpenRazer here: https://github.com/openrazer/openrazer/issues/1992, please follow that for updates. 

Another user reported this bug a few months ago for the same model.  This isn't something the app can fix, since clicking "Static" is up to OpenRazer to send the command to the hardware. Likely this laptop model expects a different command. 

A workaround for now could be to create a 'software' effect via the **Effects** tab. See also: https://github.com/polychromatic/polychromatic/issues/440#issuecomment-1268368381.

**Comment by Weuxel** [comment]
Thank you :-)
