### ISSUE TITLE
Ubuntu PPA `polychromatic/edge` is no longer signed

### ISSUE THREAD

**Issue by g0hww** [polychromatic/polychromatic#484]
Running apt update results in the following output::

```
E: Failed to fetch http://ppa.launchpad.net/polychromatic/edge/ubuntu/dists/focal/InRelease  403  Forbidden [IP: 185.125.190.52 80]
E: The repository 'http://ppa.launchpad.net/polychromatic/edge/ubuntu focal InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I think this probably relates to #479

**Comment by lah7** [comment]
`ppa:polychromatic/edge` no longer exists, the message is a bit misleading there. It's been `ppa:polychromatic/preview` since December 2022.  Is there a website or blog post that mentions this older PPA?

You can use the **Software & Updates** program (or in Linux Mint, "Software Sources") to rename `edge` to `preview`. It should work again after an apt update.

**Comment by g0hww** [comment]
Thanks, That worked. I can't point at the origin of the info I used for setting up the PPA, it has been like that for a long long time. Curious that the issue only appeared today, as there seem to be a fairly constant stream of updates to things, which are usually handled expediently.
