### ISSUE TITLE
Basilisk V3 Pro settings change at random occurences

### ISSUE THREAD

**Issue by John-Gee** [polychromatic/polychromatic#504]
### Details about the problem

I am not sure why, but sometimes the settings for my mouse change. They change while using it the computer so not related to lockscreen or shutdown. But it's possible that it happens because the mouse goes on sleep mode not sure.
The settings changing are usually the DPI and the scroll mode, sometimes the poll rate too.

I'm wondering if that means I somehow press the profile button underneath the mouse while using it, but doing so on purpose right now changes nothing.

### Operating System / Desktop Environment / Version(s)
Arch Linux, Polychromatic 0.8.3, openrazer 3.7.0.

### Affected Devices
Basilisk v3 Pro

Thanks for any advice!

**Comment by lah7** [comment]
One of three things come to mind:

* If DPI / poll rate feels the same, but the actual number in Polychromatic reads different - it could be that the device timed out and ended up with some bogus/default value. [Check `dmesg` log](https://github.com/openrazer/openrazer/wiki/Troubleshooting#where-to-find-logs) for any clues.

* OpenRazer definitely **doesn't** support that profile button underneath right now. From others' feedback with similiar mice ([#358](https://github.com/polychromatic/polychromatic/issues/358#issuecomment-936851266)) it should be left on the **white** (default) profile.  I imagine the mouse ends up in a buggy state if the hardware's chosen profile changes while in use, or maybe changing settings work but don't save properly if tried under a non-default profile? Either way, profiles [remain unknown commands.](https://github.com/openrazer/openrazer/wiki/Unknown-commands)

* Maybe if the mouse is entering sleep mode, it expects software to re-apply its last settings? The driver doesn't support that right now: https://github.com/openrazer/openrazer/issues/1143

If these clues are no good, [OpenRazer's repository](https://github.com/openrazer/openrazer/issues) would be a better place to ask this question - since Polychromatic is just displaying what `openrazer-daemon` tells us. 

Also, to potentially rule out temperamental hardware, you could try uninstalling OpenRazer, rebooting and replugging the mouse to see if it happens for a day as a generic mouse. With OpenRazer or Razer Synapse, they tell the hardware to enter ["driver mode"](https://github.com/openrazer/openrazer/wiki/Using-the-mouse-driver#device_mode---set-device-mode) so the hardware might behave differently.

**Comment by lah7** [comment]
Closing stale support issue. [OpenRazer's repository](https://github.com/openrazer/openrazer/issues) would be the best place to ask if you encounter quirky hardware behaviour.
