### ISSUE TITLE
Unable to Update System because of "Noarch/Polychromatic" - Fedora Linux 40

### ISSUE THREAD

**Issue by J0nDaGamer** [polychromatic/polychromatic#521]
When I try to perform a system upgrade, I receive this error message: 

"Cannot download noarch/polychromatic-0.8.5-1.38.noarch.rpm: All mirrors were tried; Last error: Status code: 404 for https://download.opensuse.org/repositories/hardware:/razer/Fedora_40/noarch/polychromatic-0.8.5-1.38.noarch.rpm"

I am a newbie to linux in general, and I just today downloaded this application.

If anybody could tell me a solution to this issue,

Thanks!

**Comment by lah7** [comment]
Not a Fedora user myself, but I think refreshing the metadata for the repository might be the trick.

It can be done via the terminal:

    sudo dnf upgrade --refresh

Your system seems to be looking for `polychromatic-0.8.5-1.38.noarch.rpm` instead of `polychromatic-0.8.5-1.1.noarch.rpm`. Our app [shares a repository with OpenRazer](https://download.opensuse.org/repositories/hardware:/razer/Fedora_40/noarch/).

**Comment by J0nDaGamer** [comment]
So am I unable to update as I did before?

In the console, I was told that what I was talking about is broken.

I now have a way of updating though, so thank you!

**Comment by J0nDaGamer** [comment]
This worked to complete all of my updates, besides 3 related to the issue.

**Comment by lah7** [comment]
Please do share a screenshot or copy & paste output here. I'm imagining three problematic packages come from that `hardware:/razer` repo - this app, and two packages for OpenRazer.

You could delete the faulty repo(s) -- _not sure how to do that in Fedora_ -- and then update the system before [adding the repository again](https://polychromatic.app/download/fedora/).

**Comment by J0nDaGamer** [comment]
When I use the terminal, it doesn't say that i have any issues, yet when i try and update from where I normally would, I receive the original error message.![image](https://github.com/polychromatic/polychromatic/assets/174908506/6212831a-f350-4124-a5fd-aebeb8d2f90c)

**Comment by lah7** [comment]
Apparently, according to [this answer](https://discussion.fedoraproject.org/t/dnf-update-and-discover/83926/5), the technical explanation is that KDE Discover uses PackageKit and doesn't share metadata/caches with `dnf`. I guess that means KDE Discover is checking updates independently and is outdated/mislead.

I'd try:
1. Going to **Settings tab** and disabling the `hardware:/razer` repository.
2. In the **Updates tab**, hopefully the button says "Refresh".
3. Try re-enabling the repository and see if refreshing works.

For what it's worth, you are on the latest Polychromatic version (v0.8.5) for the v0.8.x series and the system is probably up-to-date. I'm not sure why Discover/PackageKit is trying to download package revision `38` instead of `1`.

**Comment by J0nDaGamer** [comment]
Hey, i'm sorry, maybe i'm just being dumb, but what settings tab are you referring to, I didn't see anything similar to what you were talking about in my discover settings, and my polychromatic doesn't have a setting tab.

**Comment by lah7** [comment]
No worries. I might be looking at a different version, or because it was under Arch Linux (I assume Discover is similiar across distros). There was a "Settings" in the sidebar:

![image](https://github.com/polychromatic/polychromatic/assets/13032135/f217038e-178d-496f-97dd-1fbabf6bd239)

**Comment by J0nDaGamer** [comment]
No, I do have that settings, but i'm unsure what you are saying i should do. My settings looks like this: ![image](https://github.com/polychromatic/polychromatic/assets/174908506/2469f836-6869-4f70-b871-8a5ad4cc4371)![image](https://github.com/polychromatic/polychromatic/assets/174908506/56bd2ca4-6d80-4820-aa61-ccfb891d8fa0)

**Comment by lah7** [comment]
I can see `hardware:razer (Fedora_40)` in the list there, four up from the bottom. Try unchecking that, see if there's any button to "Refresh" updates (to eliminate the error message), and then try enabling and refreshing again.

We need a way to refresh the metadata from within Discover, which is behaving independently. As you saw, when using the package manager (`dnf`) directly, everything's fine and up-to-date.

**Comment by J0nDaGamer** [comment]
So I did update successfully after turning off the hardware and refreshing, but when i re-enable it, it still can't update and I am getting the same error message.

**Comment by lah7** [comment]
Sorry to hear that. Worth a try.  I'm afraid I really don't know what to do as I neither use Fedora or KDE Discover (PackageKit) to know what's going on. It would be worth asking over at [Fedora Discussions.](https://discussion.fedoraproject.org/)

The scenario is: There's a third party repository ([`hardware:razer`](https://build.opensuse.org/project/show/hardware:razer) that packages both OpenRazer and ours, Polychromatic) but KDE Discover thinks there's updates for a revision of package(s) that do not exist (`-38`, but should be `-1`). The native package manager (`dnf`) seems fine and said everything is up-to-date.

**Comment by lah7** [comment]
Didn't hear back. I'll close this issue as it's not an application fault that I can fix. Sorry to not be able to help here.

The closest I could find on Fedora Discussions is some commands that might force clear the cache:
https://discussion.fedoraproject.org/t/kde-discover-shows-updates-that-dnf-cannot-find/125719/7
