### ISSUE TITLE
Question: v0.9x Is Now QT6?

### ISSUE THREAD

**Issue by 0pLuS0** [polychromatic/polychromatic#524]
Hi,

Is 0.8.6 the last version to support QT5, 0.9x now only supports QT6?

THANKS

**Comment by lah7** [comment]
Yes, [that's correct](https://github.com/polychromatic/polychromatic/releases/tag/v0.9.0). Aside from Qt 6, v0.8.x isn't missing out on anything new, it has the same changes from v0.9.x.

The version split is because the code isn't 1:1 compatible (we use PyQt directly). It seemed simpler to keep the versions separate to track which distros need packaging for Qt 6. In some cases, users might still have a full Qt 5 environment.

I'd expect support to end for v0.8.x whenever v0.10.0 (or v1.0.0!?) is released.
