### ISSUE TITLE
Unable to install application on Linux Mint 20

### ISSUE THREAD

**Issue by hellkith** [polychromatic/polychromatic#526]
### Details about the problem

I am following the Debian guide to install the application, however I am unable to install it.
When I run the command `sudo apt install polychromatic` I get an unmet dependencies error
If I run the command to install the modules separately then I get an error about python3-pyqt6.

Is there anyway to install this application on Linux Mint 20?

### Terminal Output

```shell
username@laptop:~$ sudo apt install polychromatic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 polychromatic : Depends: polychromatic-controller but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
username@laptop:~$ sudo apt install polychromatic-controller polychromatic-tray-applet polychromatic-cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 polychromatic-controller : Depends: python3-pyqt6 but it is not installable
                            Depends: python3-pyqt6.qtsvg but it is not installable
                            Depends: python3-pyqt6.qtwebengine but it is not installable
                            Depends: pyqt6-dev-tools but it is not installable
E: Unable to correct problems, you have held broken packages.
username@laptop:~$
```

### Application Version

-

### Qt Version

-

### Operating System

Linux Mint 20

**Comment by lah7** [comment]
While Linux Mint is technically based on Debian, it's actually based on Ubuntu first - except for the [Linux Mint Debian Edition](https://www.linuxmint.com/download_lmde.php) (LMDE) which is a separate release.

To install, you should follow the [Ubuntu instructions](https://polychromatic.app/download/ubuntu/) instead. However, since it does share a repository with Debian, we can just correct the codename used for the PPA. You're seeing this error since it's looking for packages designed for a newer distro.

Linux Mint 20 is [based on Ubuntu 20.04 LTS](https://en.wikipedia.org/wiki/Linux_Mint#Ubuntu-based_editions), so the codename will be `focal`. To correct the problem:

1. Open Software Sources.
2. Choose "PPA" in the sidebar.
3. Choose "polychromatic/stable" and edit the entry.
4. At the end, the second to last word should be `focal`.
5. Click OK to update the cache.
6. Try installing again (e.g. `sudo apt install polychromatic`)

![Software Sources in Linux Mint 22](https://github.com/user-attachments/assets/00f8d998-af1f-40fa-b4a3-abc43d01a1b3)

**Comment by hellkith** [comment]
Aha, I removed the sources entirely and re-followed the installation instructions and it worked!
Thanks for the help :D
